from __future__ import annotations

import csv
import json
from pathlib import Path

from scripts.materialize_lil_deep_route_v101 import SC2_SHA256

ROOT = Path(__file__).resolve().parents[1]
LINES = {
    (227, 5): "Hyah! Ha!",
    (227, 9): "Yawn... Oh, Yifa! You're training.",
    (227, 12): "To face someone with a sword takes real courage.",
    (227, 15): "Being afraid makes you hesitate and gets you hurt worse. You need the resolve to face things without fear.",
    (227, 18): "Heard of a martial arts robe so tough that blades chip when they strike it?",
    (227, 21): "A cloth robe? Not armor? Really?",
    (227, 25): "With that, you could fight without holding back...",
    (227, 28): "Oops! Master would scold me for relying on gear. 'Train yourself first!' he'd say.",
    (227, 32): "Back to training! Hyah!",
    (228, 5): "Admiral, a moment?",
    (228, 9): "Yes? What?",
    (228, 13): "Just heard about an animal called an armadillo. Know it? They say its hide is harder than iron.",
    (228, 17): "Hmm.",
    (228, 21): "Someone once made a shield from its hide. They called it Armadillo's Steel Hide.",
    (228, 24): "So? What's your point?",
    (228, 28): "You're slow! A shield harder than iron! Don't you want one? Just think how useful it'd be in battle!",
    (228, 31): "Oh, right! Where is it?",
    (228, 34): "Well... All we know is that it's hidden somewhere in Africa.",
    (228, 38): "What? That's hardly enough to go searching on!",
    (228, 42): "Well, yes, but...",
    (228, 46): "Cheer up! We'll remember it. With luck, we might find it!",
    (228, 50): "Right!",
    (229, 5): "Admiral, a moment?",
    (229, 9): "Yes? What?",
    (229, 13): "Just heard about giant tortoises. Know them? Their shells are said to be harder than iron.",
    (229, 16): "Hmm.",
    (229, 20): "Someone made a shield from one of those shells. They call it the Giant Tortoise Shield.",
    (229, 23): "Sounds familiar... Didn't you say that about some armadillo thing?",
    (229, 27): "Really? Can't remember.",
    (229, 31): "Well, never mind. What about it?",
    (229, 34): "Don't you want one? A shield like that would be great in battle!",
    (229, 38): "That's exactly what you said about the armadillo thing.",
    (229, 41): "Really? Never mind that!",
    (229, 45): "All right, then. Where can we find it?",
    (229, 48): "All we know is that it's hidden around the ocean south of Asia.",
    (229, 51): "That's no help at all!",
    (229, 55): "Well, yes, but...",
    (229, 59): "Cheer up! We'll remember it. With luck, we might find it!",
    (229, 63): "Right!",
    (230, 5): "Admiral, a moment?",
    (230, 9): "Yes? What?",
    (230, 13): "Are phoenixes real, Admiral?",
    (230, 17): "Phoenixes? Seeing one would be fun! Why ask all of a sudden?",
    (230, 21): "There's a helmet forged in a phoenix's flames. The Phoenix Bascinet, they call it.",
    (230, 24): "Don't tell me we should get it because it'd help in battle!",
    (230, 28): "Wow! How did you know?",
    (230, 32): "You've said it before! Don't you remember?",
    (230, 36): "Really? What a memory!",
    (230, 40): "You're so forgetful! Where's this one? Don't tell me it's somewhere in Africa or southern Asia again!",
    (230, 43): "What? This one's in Britain!",
    (230, 47): "Oh! That narrows it down!",
    (230, 50): "Ahem! Did my research! The first clue only said northern Europe.",
    (230, 54): "Nice work! Well researched!",
    (230, 58): "Hehe, sure!",
    (230, 62): "Then we'll keep the Phoenix Bascinet in mind. We'll find it someday!",
    (230, 66): "Yes! Hope we get it!",
    (231, 5): "Do you know Herophilus?",
    (231, 9): "No. Who's that? What about him?",
    (231, 12): "An ancient physician. He wrote the world's oldest medical book.",
    (231, 16): "Oh?",
    (231, 20): "They say the book describes ways to keep sailors from tiring...",
    (231, 24): "Amazing! We have to get it if that's true!",
    (231, 28): "Certainly.",
    (231, 32): "But where is it? Do you know?",
    (231, 35): "Someone saw it long ago at the far end of the Mediterranean, so they say.",
    (231, 39): "And then?",
    (231, 43): "That's all.",
    (231, 47): "Hmm. No help there.",
    (231, 50): "My apologies.",
    (231, 54): "Don't apologize!",
    (231, 58): "Yes...",
    (231, 62): "To get it, we must sail to the Mediterranean.",
    (233, 5): "Admiral, a moment?",
    (233, 8): "What?",
    (233, 12): "A curious scrap of paper turned up at Alexandria's library lately.",
    (233, 16): "Paper? About?",
    (233, 20): "About a wondrous chisel once used by Phidias, the legendary sculptor of ancient Greece, to make his works.",
    (233, 23): "A chisel? Used with a hammer to carve wood or stone?",
    (233, 26): "Yes. They say his soul entered it upon his death. Whoever uses it gains a miraculous gift for shaping things.",
    (233, 29): "The chisel is buried somewhere on the Balkan Peninsula near Greece. The paper gave no precise location.",
    (233, 32): "Manuel, you want to repair ships with that chisel?",
    (233, 36): "Why not? The Romans even used kings as their tools of policy. Rather grand tools, don't you think?",
    (233, 39): "Ships are works of art too. They deserve fine tools! Have a look for it when you get the chance.",
    (234, 9): "What's wrong, my friend? Daydreaming?",
    (234, 12): "Eh? Carlo! You're back! When did you arrive?",
    (234, 16): "Just here on business. But you'll never draw customers with that vacant look on your face!",
    (234, 19): "Mind your business! Still, talking like that... You seem to be yourself again.",
    (234, 23): "Yes. Back in action at last. Sailing with these people now.",
    (234, 26): "Oh! Customers? Sorry. Lost in thought, recalling a tale my great-grandfather told me.",
    (234, 29): "What tale?",
    (234, 33): "Papal trade. The pope once ruled land almost as far as Venice.",
    (234, 37): "Heard of that. When papal power was at its height, trade flourished in those lands.",
    (234, 40): "Right. Nobles competed over how much to give the pope, and what to give...",
    (234, 43): "Our ancestors made fortunes just moving goods around. But these days...",
    (234, 47): "The pope's power waned, and trade with the Church declined.",
    (234, 51): "Right. We're back to earning our living through hard work. How lucky my great-grandfather was!",
    (234, 54): "Come to think of it, objects linked to the pope still turn up in lands he once ruled.",
    (234, 57): "So they say. Something a pope used might carry a blessing. Ah, could use some divine favor myself!",
    (234, 60): "God's favor...",
    (234, 64): "Admiral, he may have a point. An object a pope treasured would be quite a discovery.",
    (235, 14): "Admiral, a letter from Charles.",
    (235, 15): "Admiral, a letter from Charles.",
    (235, 16): "Admiral, a letter from Charles.",
    (235, 17): "Admiral, a letter from Charles.",
    (235, 18): "Admiral, a letter from Charles.",
    (235, 19): "Admiral, a letter from Charles.",
    (235, 20): "Admiral! A letter from Charles!",
    (235, 27): "Now in West Africa. Some sailors here told me a strange story worth sharing with you.",
    (235, 31): "Pirates attacked Spanish traders sailing from the New World to West Africa.",
    (235, 35): "Outmatched, the merchants fled. But they were slower, and their destruction seemed inevitable.",
    (235, 38): "Yet far out at sea west of Lisbon, they heard an unearthly roar.",
    (235, 41): "The sound gave the sailors new courage. They fought like lions, holding their own against the pirates.",
    (235, 44): "They held out until a Spanish naval fleet happened by. The pirates scattered, and the merchant ships narrowly escaped disaster.",
    (235, 47): "No one knows what made the sound, or whether science can explain it as a natural phenomenon.",
    (235, 50): "An intriguing tale, all the same. You might enjoy investigating it. -- Charles Jean Rochefort",
    (235, 57): "That's a bit creepy... What made that roar? Surely not a monster?",
    (236, 14): "Admiral, a letter from Jam.",
    (236, 15): "Admiral, a letter from Jam.",
    (236, 16): "Admiral, a letter from Jam.",
    (236, 17): "Admiral, a letter from Jam.",
    (236, 18): "Admiral, a letter from Jam.",
    (236, 19): "Admiral, a letter from Jam.",
    (236, 20): "Admiral! A letter from Jam!",
    (236, 27): "Hey, Admiral! Everyone doing well?",
    (236, 30): "This land of the Ganges is incredible! Can't sum it up in a few words. Oh, right! Heard a pretty interesting rumor.",
    (236, 33): "There's a sacred beast statue made under the Gupta dynasty. Seems it can see the future!",
    (236, 36): "Sounds fishy, right? But anything can happen in this land. Maybe there's truth to it.",
    (236, 39): "With that, maybe even Peres would lose to me at gambling! Too hopeful?",
    (236, 42): "But nobody sells it, and nobody seems to have seen it either.",
    (236, 46): "Why not look for it when you've got time, Admiral? That might be useful for more than gambling!",
    (236, 49): "Oops, time to sail! Hope you find that treasure. See you! -- Jam Jack Ludwyan",
    (236, 64): "Ha! He'll need 500 more years to beat me, even with that!",
    (236, 70): "What did he go there for? Still, that sounds interesting. Worth remembering.",
    (237, 5): "Hmph! What are they talking about?!",
    (237, 8): "Cesare, why so angry?",
    (237, 12): "The sailors are spouting nonsense!",
    (237, 15): "Nonsense?",
    (237, 19): "Skipping work! 'Demon-Piercing Arrow' indeed! Oh, that's the item's name. Quite a grand name at that!",
    (237, 22): "You've lost me. What is it?",
    (237, 25): "A legendary arrow that an angel used to slay a demon, so they say!",
    (237, 29): "Supposedly, it makes you a master archer. They wonder if it works on cannons too, instead of maintaining the ship!",
    (237, 32): "Practicing with the cannons would help far more than gossiping about that!",
    (237, 36): "As if such a thing were lying around near Britain! They say it's on Skye, or that someone saw it on Lewis!",
    (237, 39): "All worked up over silly rumors! Were it so close, someone would have found it by now!",
    (237, 42): "... (Can't deal with him.)",
    (237, 45): "Those men are always like this! Grumble... grumble...",
    (238, 5): "Ouch! ... Ow...",
    (238, 9): "Janus? What happened?",
    (238, 12): "Nothing serious. Caught my hand on a mast fitting while tending the ship.",
    (238, 16): "Hey, lad! What's wrong?",
    (238, 19): "Well... um...",
    (238, 23): "He hurt his hand.",
    (238, 26): "That's no good. Let me see.",
    (238, 29): "Ouch...",
    (238, 33): "Hmm. The sort of wound a sailor knows well.",
    (238, 36): "Hehe. There's a pair of gloves to prevent that.",
    (238, 40): "Gloves",
    (238, 44): "Yes! You won't find gloves this good elsewhere. Wait a moment... Where'd they go...?",
    (238, 47): "Oh no! Did they fall out somewhere?",
    (238, 50): "Hey! Did you really have them?",
    (238, 53): "Sorry! Must've dropped them... Oh! Somewhere near Denmark!",
    (238, 57): "Denmark, you say?",
    (238, 61): "Yes! The Jutland Peninsula, for sure! Really! Believe me!",
    (238, 65): "Okay. We'll look.",
    (238, 69): "You believe me? Good! They're yours if you find them!",
    (238, 73): "They don't fit my hands, so they were for sale anyway. But their effect is guaranteed!",
}
BARE = {(b, n) for b in (235, 236) for n in range(15, 21)}
SPEAKERS = {0x02: "Lil", 0x04: "Janus", 0x0B: "Jam", 0x0D: "Cesare", 0x12: "Charles", 0x13: "Carlo", 0x14: "Peres", 0x16: "Sanghyeon", 0x17: "Manuel", 0x19: "Yifa", 0x68: "Merchant", 0x71: "Sailor", 0xD0: "Companion report"}
CONTEXT = {227: "Yifa trains and mentions the blade-resistant martial arts robe.", 228: "Sanghyeon's armadillo shield clue in Africa.", 229: "Sanghyeon's giant tortoise shield clue around the Indian Ocean.", 230: "Sanghyeon's Phoenix Bascinet research narrows the location to Britain.", 231: "Carlo's Herophilus medical book clue in the far Mediterranean.", 233: "Manuel's Phidias chisel clue in the Balkans near Greece.", 234: "Carlo and his merchant friend discuss papal trade and relics.", 235: "Charles's letter about the mysterious roar west of Lisbon; all deliveries.", 236: "Jam's Gupta sacred beast letter from India and Fernando's reaction; all deliveries.", 237: "Cesare complains about the demon arrow rumors on Skye and Lewis.", 238: "Janus's injury and the sailor's lost gloves on the Jutland Peninsula."}


def main() -> None:
    with (ROOT / "work/sc2/script.csv").open(encoding="utf-8-sig", newline="") as stream:
        source = {row["id"]: row for row in csv.DictReader(stream)}
    expected = {i for i in source if 227 <= int(i.split("_B")[1].split("_")[0]) <= 238}
    assert expected == {f"DK4_MES_B{b}_R{n:04d}" for b, n in LINES}
    records = []
    for (b, n), text in LINES.items():
        row_id = f"DK4_MES_B{b}_R{n:04d}"
        raw = bytes.fromhex(source[row_id]["source_hex"])
        state = None if (b, n) in BARE else raw[0]
        assert state is None or state in SPEAKERS
        assert "I" not in text and "F" not in text
        records.append({"id": row_id, "english": ("" if state is None else f"{{SPEAKER:{state:02X}}}") + text + "{PAD}", "speaker": SPEAKERS.get(state, "Bare companion report"), "context": CONTEXT[b], "source_meaning": text, "source_japanese": raw[int(state is not None):].decode("shift_jis", errors="replace"), "localization_note": "Source-reviewed natural English preserves treasure clues and delivery variants. Peres and geographic epithets avoid unsafe capital F/I renderer bytes.", "review": {g: True for g in ("source", "context", "localization", "naturalness", "formatting")}})
    batch = {"format": "dk4-ilnk-translation-batch-v1", "file_path": "/data/SC2.DK4", "source_file_sha256": SC2_SHA256, "encoder": "dialogue-fixed-v1", "dialogue_profile": "lil-story-deep-route-v103-live", "translation_policy": "natural-dialogue-v2", "target_locale": "en-US", "review_gates": ["source", "context", "localization", "naturalness", "formatting"], "scope": "All B227-B238 companion treasure clues and letters; B232 is empty.", "inventory": {"identified_records": len(expected), "translated_records": len(records), "blocks": {str(b): sum(bb == b for bb, _ in LINES) for b in CONTEXT}}, "excluded_records": {}, "records": records}
    (ROOT / "translations/lil_deep_route_v103.json").write_text(json.dumps(batch, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote Lil V103: {len(records)} records")


if __name__ == "__main__":
    main()
