from __future__ import annotations
import csv,json
from pathlib import Path
S=Path("work/sc3/script.csv");O=Path("translations/maria_deep_route_v107.json");SHA="001e21897ddb727ae261c82763ebef8515784ecfa571619c7614d87f3320aab2"
L={
"DK4_MES_B144_R0005":"Ah, {MACRO:FI}...","DK4_MES_B144_R0009":"When did you two meet?","DK4_MES_B144_R0013":"Mihwa, she found the crown.{LB}This man only received it from her.","DK4_MES_B144_R0017":"The Golden Crown of Silla...{LB}Such radiant gold.{LB}Breathtakingly beautiful...","DK4_MES_B144_R0021":"As promised, it's yours!","DK4_MES_B144_R0025":"Wonderful!{LB}Treasured forever. Thank you!","DK4_MES_B144_R0028":"Good for you.","DK4_MES_B144_R0032":"Yes, thanks to you.{LB}Now this man owes you.","DK4_MES_B144_R0035":"No need.","DK4_MES_B144_R0039":"A debt is owed to {MACRO:FO}'s{LB}Admiral {MACRO:FI}.{LB}Let me work aboard your ship.","DK4_MES_B144_R0042":"{LB}Is that truly repayment...?","DK4_MES_B144_R0045":"Don't worry about skill.{LB}My grandfather sailed the world.{LB}Ships inspired me since childhood.","DK4_MES_B144_R0048":"An adventurer like Grandfather!{LB}The world is calling!","DK4_MES_B144_R0052":"{LB}The world, eh?{LB}His grandfather's spirit lives on.","DK4_MES_B144_R0055":"...All right. Your courage in Seoul{LB}won me over. Sail with us.","DK4_MES_B144_R0059":"Yes!{LB}Traveling with such a beauty{LB}will be wonderful...","DK4_MES_B144_R0063":"Julian?","DK4_MES_B144_R0067":"Sorry, Mihwa. Don't be jealous.{LB}She's only my new employer.","DK4_MES_B144_R0071":"Once something finer is found{LB}than the crown, this man returns.{LB}Then we date!","DK4_MES_B144_R0075":"Really, Julian...{LB}Waiting, then.","DK4_MES_B144_R0078":"Hopefully this voyage{LB}isn't spent wooing women...",
"DK4_MES_B146_R0004":"Hm?","DK4_MES_B146_R0008":"...Did Yukihisa find any clue{LB}to that sword?","DK4_MES_B146_R0012":"No. Nothing yet.","DK4_MES_B146_R0015":"Huh.{LB}Does it even exist?","DK4_MES_B146_R0018":"Who knows.","DK4_MES_B146_R0027":"Yukihisa.","DK4_MES_B146_R0031":"Admiral.","DK4_MES_B146_R0035":"A sword is being sought?","DK4_MES_B146_R0039":"You heard? Perhaps it is rumor.{LB}We crossed the world{LB}without one clue.","DK4_MES_B146_R0042":"Help would be given if possible.","DK4_MES_B146_R0045":"No. Unrelated to our mission.{LB}Do not trouble yourself.","DK4_MES_B146_R0049":"...Would you sail to Japan alone?","DK4_MES_B146_R0052":"What?","DK4_MES_B146_R0056":"There is no time while with us.{LB}Take command of a fleet{LB}and search at leisure.","DK4_MES_B146_R0059":"That cannot be!{LB}Company ships cannot be borrowed{LB}for a private matter!","DK4_MES_B146_R0063":"Honorable as ever.{LB}But choosing one who knows the region{LB}is sound command.","DK4_MES_B146_R0067":"Admiral...{LB}Thank you.",
}
L["DK4_MES_B144_R0042"]="{LB}That counts as repayment...?"
L["DK4_MES_B144_R0028"]="Good."
L["DK4_MES_B144_R0055"]="...All right. Your courage in Seoul{LB}won me over. Join us."
L["DK4_MES_B144_R0078"]="Hope the voyage{LB}isn't spent flirting."
L["DK4_MES_B146_R0018"]="Maybe."
L["DK4_MES_B146_R0027"]="Yuki..."
SP={"03":"Maria","0B":"Jam","0C":"Yukihisa","15":"Ian","1A":"Julian","C9":"Mihwa"};ST={int(x,16) for x in SP};C={144:"Julian gives Mihwa the Golden Crown of Silla, then joins Maria to become an adventurer.",146:"Maria grants Yukihisa independent fleet command so he can continue searching Japan for his sword."}
def main()->None:
 with S.open(encoding="utf-8-sig",newline="") as f:rows={r["id"]:r for r in csv.DictReader(f) if int(r["id"].split("_B",1)[1].split("_R",1)[0]) in {144,146}}
 if set(L)!=set(rows):raise SystemExit(f"V107 mismatch: missing={sorted(set(rows)-set(L))}; extra={sorted(set(L)-set(rows))}")
 rec=[]
 for i in sorted(L,key=lambda v:(int(v.split("_B",1)[1].split("_R",1)[0]),int(v.rsplit("R",1)[1]))):
  r=rows[i];e=L[i];first=bytes.fromhex(r["source_hex"])[0];state=f"{first:02X}" if first in ST else "";u=e.replace("{MACRO:FI}","").replace("{MACRO:FA}","").replace("{MACRO:FO}","")
  if "F" in u or "I" in u:raise SystemExit(f"{i}: unsafe macro literal: {e}")
  sb=r["japanese"].count("{LB}");tb=e.count("{LB}");w=["weak-line-ending","orphan-final-line"]+(["manual-break"] if tb else [])+(["source-leading-linebreak"] if r["japanese"].startswith("{LB}") else [])+(["line-break-count"] if sb!=tb else []);prefix=f"{{SPEAKER:{state}}}" if state else "";b=int(i.split("_B",1)[1].split("_R",1)[0])
  rec.append({"id":i,"english":f"{prefix}{e}{{PAD}}","speaker":SP.get(state,"Xien continuation"),"context":C[b],"source_meaning":e.replace("{LB}"," "),"localization_note":"Direct SC3 translation preserving recruitment and command beats, FI/FO macro order, speaker states, line breaks, and fixed allocation.","qa_waivers":w,**({"manual_break_reason":"Protects semantic rows and progressive ASCII pair phase."} if tb else {}),"review":{"source":True,"context":True,"localization":True,"naturalness":True,"formatting":True}})
 p={"format":"dk4-ilnk-translation-batch-v1","file_path":"/data/SC3.DK4","source_file_sha256":SHA,"encoder":"dialogue-fixed-v1","dialogue_profile":"maria-story-shared-events-v107-live","translation_policy":"natural-dialogue-v2","target_locale":"en-US","review_gates":["source","context","localization","naturalness","formatting"],"scope":"Maria SC3 blocks 144 and 146: Julian recruitment and Yukihisa sword search.","excluded_records":{},"inventory":{"identified_records":38,"translated_records":38,"excluded_records":0,"blocks":{"144":21,"146":17}},"records":rec};O.write_text(json.dumps(p,ensure_ascii=False,indent=2)+"\n",encoding="utf-8");print(f"wrote {O}: {len(rec)} translations")
if __name__=="__main__":main()
