from __future__ import annotations
import csv,json
from pathlib import Path
SOURCE=Path('work/sc3/script.csv');OUTPUT=Path('translations/maria_deep_route_v57.json');SC3_SHA256='001e21897ddb727ae261c82763ebef8515784ecfa571619c7614d87f3320aab2';BLOCKS=(48,49,50)
LINES={
'DK4_MES_B48_R0005':'Raphael.{LB}Watch yourself.',
'DK4_MES_B48_R0009':'You are right, Crow.{LB}A pirate that fearsome?{LB}The world truly is vast.',
'DK4_MES_B48_R0013':'Dreadful hardly covers it.{LB}That woman, {MACRO:FA}...',
'DK4_MES_B48_R0021':'She disarms foes with schemes,{LB}then slaughters them off guard.{LB}Cross her, and a dozen lives{LB}would not save you.',
'DK4_MES_B48_R0025':'Heh heh.',
'DK4_MES_B48_R0030':'Hm?',
'DK4_MES_B48_R0034':'Hey, woman!{LB}What is so funny?!',
'DK4_MES_B48_R0037':'Pardon me.{LB}Tell me more.{LB}What does she look like?',
'DK4_MES_B48_R0041':'Never saw her myself,{LB}so who knows?{LB}Probably has the face of a demon.',
'DK4_MES_B48_R0045':'They say she has short black hair,{LB}black clothes, a crimson coat...',
'DK4_MES_B48_R0050':'What?!',
'DK4_MES_B48_R0054':'A crimson rose...{LB}W-wait. Are you...?!',
'DK4_MES_B48_R0057':'Me?{LB}{MACRO:FI} {MACRO:FA}.{LB}A pleasure.',
'DK4_MES_B48_R0061':'Y-you are{LB}{MACRO:FA}?',
'DK4_MES_B48_R0071':'Ahem!{LB}Exactly.',
'DK4_MES_B48_R0079':'Eek! So it is you!!{LB}No, forgive me!{LB}Please spare my life!!',
'DK4_MES_B48_R0084':'Such a beautiful person...{LB}Crow, the rumors must be nonsense.',
'DK4_MES_B48_R0088':'Y-yes! Such a beautiful lady{LB}cannot be that dreadful pirate!{LB}Ahaha!',
'DK4_MES_B48_R0098':'A smooth talker.',
'DK4_MES_B48_R0108':'No flattery.{LB}Yes, {MACRO:FA} is my name.{LB}Many people seem to fear it.',
'DK4_MES_B48_R0111':'But my targets rule by force{LB}and steal the people\'s wealth.{LB}Do you help such men?',
'DK4_MES_B48_R0114':'N-never!{LB}We earn an honest living{LB}through honest trade. Right?',
'DK4_MES_B48_R0119':'Portugal once ruled the world.',
'DK4_MES_B48_R0143':'Spain has taken the lead now,{LB}but we dream of making Portugal{LB}a lively nation of sailors again.',
'DK4_MES_B48_R0146':'So Portugal should replace Spain{LB}and rule the world?',
'DK4_MES_B48_R0151':'Spain\'s conquest of the New World{LB}is not what we seek.',
'DK4_MES_B48_R0155':'Then Spain is wrong{LB}and Portugal is right?',
'DK4_MES_B48_R0159':'...No. Portugal\'s old methods{LB}were not right either.',
'DK4_MES_B48_R0163':'We only want goods to flow fairly.{LB}Then both seller and buyer{LB}can prosper.',
'DK4_MES_B48_R0167':'Through shipping, people everywhere{LB}might live a little better.{LB}That is the role we seek.',
'DK4_MES_B48_R0171':'Rafi... You thought{LB}about all that?',
'DK4_MES_B48_R0174':'Hmm. A worthy ideal.',
'DK4_MES_B48_R0179':'Was that rude?{LB}Sorry for sounding grand.',
'DK4_MES_B48_R0182':'No, that is not what was meant.{LB}Would that every sailor{LB}thought as you do.',
'DK4_MES_B48_R0194':'Enough philosophy.{LB}Do you know the Mediterranean?{LB}What is happening there now?',
'DK4_MES_B48_R0198':'Recent news? Hmm...',
'DK4_MES_B48_R0211':'Spain\'s Valdes fleet is strongest.{LB}Since losing at Lepanto,{LB}the Ottoman navy is nearly ruined.',
'DK4_MES_B48_R0217':'Spain and the Ottoman Turks{LB}hold most interests there.{LB}Admirals Valdes and Pasha{LB}keep skirmishing.',
'DK4_MES_B48_R0228':'Hayreddin\'s fleet held{LB}the Strait of Gibraltar,{LB}the Mediterranean gateway, but...',
'DK4_MES_B48_R0240':'After their Turkish alliance ended,{LB}their main force withdrew east.{LB}Now they are rarely seen.',
'DK4_MES_B48_R0246':'When their Turkish alliance ended,{LB}their main force{LB}withdrew east.',
'DK4_MES_B48_R0254':'Understood. That is enough.{LB}Thank you. May we ask your help again?{LB}We will aid you in return.',
'DK4_MES_B48_R0257':'Of course! Against Spain,{LB}we will join you at once. Right?',
'DK4_MES_B48_R0262':'Certainly. We are glad to help.{LB}Please call on us.',
'DK4_MES_B49_R0005':'Hmph.{LB}More trouble arrives.',
'DK4_MES_B49_R0019':'That is Maldonado!',
'DK4_MES_B49_R0025':'{LB}That is Maldonado!',
'DK4_MES_B49_R0032':'Maldonado...',
'DK4_MES_B49_R0043':'He leads Caribbean pirates.',
'DK4_MES_B49_R0048':'{LB}He leads Caribbean pirates.',
'DK4_MES_B49_R0063':'Pirate',
'DK4_MES_B49_R0070':'Why seek me, pirate?',
'DK4_MES_B49_R0074':'Easy. Do not bare your fangs.{LB}No wish to fight you.{LB}My position is desperate enough.',
'DK4_MES_B49_R0085':'That Escante dog proposed we strike{LB}England\'s Clifford together,{LB}then betrayed us once the foe fell.',
'DK4_MES_B49_R0096':'That Escante dog proposed we strike{LB}England\'s Clifford together,{LB}then betrayed us when the foe held.',
'DK4_MES_B49_R0101':'Escante and England\'s Clifford{LB}caught us between them,{LB}and now the Swedes intrude too.',
'DK4_MES_B49_R0110':'Why make more enemies?{LB}You only tighten your own noose.',
'DK4_MES_B49_R0113':'And if you will not fight,{LB}but we do?',
'DK4_MES_B49_R0116':'What?!',
'DK4_MES_B49_R0120':'Think we ignore pirates{LB}who disrupt shipping{LB}and torment people?',
'DK4_MES_B49_R0123':'Hey, now.{LB}Never did anything to anger you.',
'DK4_MES_B49_R0126':'Did you not?',
'DK4_MES_B49_R0130':'The gold Escante ships home{LB}was taken by force{LB}from New World peoples{LB}to buy his weapons.',
'DK4_MES_B49_R0133':'Why complain when we seize it?',
'DK4_MES_B49_R0136':'Many of us are natives{LB}or of mixed blood.{LB}We reclaim stolen treasure.{LB}What is wrong with that?',
'DK4_MES_B49_R0139':'That is sophistry.{LB}You merely exploit{LB}the feelings of local people.',
'DK4_MES_B49_R0143':'Exploit? Of course.{LB}They use my strength for revenge{LB}and earn food to live.{LB}Each side gains.',
'DK4_MES_B49_R0150':'Believe it or not.{LB}Will you join me against Escante?{LB}You cannot condone his tyranny.',
'DK4_MES_B49_R0153':'He rules people by force{LB}and strips away wealth{LB}built over generations.',
'DK4_MES_B49_R0157':'When nothing remains to steal,{LB}he makes them labor{LB}on his plantations.{LB}Can that stand?',
'DK4_MES_B49_R0160':'Pirate lecturing me{LB}on right and wrong?{LB}Hard to believe it sincere.',
'DK4_MES_B49_R0164':'Heh heh. Profit is my real aim.{LB}No denying that. But...',
'DK4_MES_B49_R0167':'Better to rob the truly wicked.{LB}My men rejoice, and Escante{LB}gnashes his teeth.{LB}Both sights please me.',
'DK4_MES_B49_R0174':'The enemy of my enemy, yes?{LB}Join me and bring down{LB}that dog Escante. What say you?',
'DK4_MES_B49_R0179':'Watch him awhile.',
'DK4_MES_B49_R0181':'Enough!',
'DK4_MES_B49_R0188':'Very well.{LB}We decide whether to fight{LB}after seeing what you do.',
'DK4_MES_B49_R0192':'Good. A deal.{LB}Leave these waters to me.{LB}Escante will be kept in check.',
'DK4_MES_B49_R0195':'A convenient bargain.{LB}The Caribbean is yours for now.{LB}Betray its people, and we crush you.',
'DK4_MES_B49_R0198':'Heh. Try it if you can.{LB}No need to fear betrayal.',
'DK4_MES_B49_R0201':'...Perhaps',
'DK4_MES_B49_R0209':'Enough.{LB}We did not come{LB}to hear your excuses.',
'DK4_MES_B49_R0213':'So an outsider like you{LB}cannot understand this place.',
'DK4_MES_B49_R0217':'Make me your enemy, then.{LB}But you will not have your way.{LB}The Caribbean pirates{LB}will show their mettle.',
'DK4_MES_B50_R0008':'Xien?',
'DK4_MES_B50_R0012':'{LB}T-terrible news!!{LB}Richard defected{LB}to Clifford\'s fleet!!',
'DK4_MES_B50_R0016':'Richard?!',
'DK4_MES_B50_R0024':'Hangzhou',
'DK4_MES_B50_R0029':'Heh.',
'DK4_MES_B50_R0033':'Heh heh...{LB}Hahahahaha!!',
'DK4_MES_B50_R0036':'At last the time has come...{LB}England will finally{LB}claim the seas of the world!',
'DK4_MES_B50_R0040':'{MACRO:FI}...{LB}You went too far...',
'DK4_MES_B50_R0043':'Had you stayed in the East{LB}and merely policed the wako,{LB}England might have welcomed you{LB}as a capable servant...',
'DK4_MES_B50_R0046':'You truly enraged{LB}the English...',
'DK4_MES_B50_R0049':'With {MACRO:FI} away,{LB}our long-planned scheme{LB}can be completed...',
'DK4_MES_B50_R0053':'No home remains for you{LB}This man becomes{LB}East Asia\'s Governor-General.{LB}Heh heh...',
'DK4_MES_B50_R0057':'A delightful time,{LB}beautiful Admiral.',
'DK4_MES_B50_R0060':'Lord Clifford...{LB}Expect good news.',
'DK4_MES_B50_R0076':'Most Ming shares{LB}have fallen into{LB}Clifford\'s hands!!',
}
EXCLUDED={'DK4_MES_B48_R0252':'nontext event payload 90 46 7D 80; preserved byte-for-byte'}
STATES={0x03,0x05,0x1B,0x2A,0x4A,0xFE};SPEAKERS={'03':'Maria','05':'Crow','1B':'Companion','2A':'Maldonado','4A':'Richard','FE':'Narration or off-screen voice'}
def main()->None:
 with SOURCE.open(encoding='utf-8-sig',newline='') as source:all_rows={r['id']:r for r in csv.DictReader(source)}
 rows={i:r for i,r in all_rows.items() if any(i.startswith(f'DK4_MES_B{b:02d}_') for b in BLOCKS)}
 if set(LINES)|set(EXCLUDED)!=set(rows):raise SystemExit(f'V57 mismatch: missing={sorted(set(rows)-set(LINES)-set(EXCLUDED))}, extra={sorted((set(LINES)|set(EXCLUDED))-set(rows))}')
 records=[];counts={str(b):0 for b in BLOCKS}
 for i in sorted(LINES,key=lambda v:(int(v.split('_B',1)[1].split('_',1)[0]),int(v.rsplit('R',1)[1]))):
  r=rows[i];e=LINES[i];first=bytes.fromhex(r['source_hex'])[0];state=f'{first:02X}' if first in STATES and not r['japanese'].startswith('{LB}') else '';counts[str(int(i.split('_B',1)[1].split('_',1)[0]))]+=1;sb=r['japanese'].count('{LB}');tb=e.count('{LB}');waivers=['weak-line-ending','orphan-final-line']+(['manual-break'] if tb else [])+(['source-leading-linebreak'] if e.startswith('{LB}') else [])+(['line-break-count'] if sb!=tb else [])
  records.append({'id':i,'english':f'{{SPEAKER:{state}}}{e}{{PAD}}' if state else f'{e}{{PAD}}','speaker':SPEAKERS.get(state,'Scene speaker'),'context':'Maria route: meeting Raphael and Crow, debate over fair trade and Mediterranean powers, Maldonado alliance branches, and Richard\'s betrayal in Hangzhou.','source_meaning':e.replace('{LB}',' '),'localization_note':'Direct SC3 translation preserving route crossovers, alternate branches, political exposition, portrait states, name macros, source staging, and fixed allocation.','qa_waivers':waivers,**({'manual_break_reason':'Preserves source staging or groups the thought within the source display.'} if tb else {}),'review':{'source':True,'context':True,'localization':True,'naturalness':True,'formatting':True}})
 payload={'format':'dk4-ilnk-translation-batch-v1','file_path':'/data/SC3.DK4','source_file_sha256':SC3_SHA256,'encoder':'dialogue-fixed-v1','dialogue_profile':'maria-story-shared-events-v57-live','translation_policy':'natural-dialogue-v2','target_locale':'en-US','review_gates':['source','context','localization','naturalness','formatting'],'scope':'Maria SC3 blocks 48-50: Raphael and Crow meeting, fair-trade debate, Mediterranean intelligence, Maldonado alliance branches, and Richard\'s betrayal.','inventory':{'identified_records':len(rows),'translated_records':len(records),'excluded_records':len(EXCLUDED),'blocks':counts},'excluded':[{'id':i,'reason':r} for i,r in EXCLUDED.items()],'records':records}
 OUTPUT.write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n',encoding='utf-8');print(f'wrote {OUTPUT}: {len(records)} records, {len(EXCLUDED)} preserved control')
if __name__=='__main__':main()
