from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Arm9ProfileEntry:
    row_id: str
    offset: int
    japanese: str
    suggested_english: str
    context: str
    notes: str = ""
    slot_size: int | None = None

    @property
    def source_bytes(self) -> bytes:
        return self.japanese.encode("cp932")

    @property
    def source_length(self) -> int:
        return self.slot_size or len(self.source_bytes)

    @property
    def expected_bytes(self) -> bytes:
        source = self.source_bytes
        return source + b"\0" * (self.source_length - len(source))


STARTUP_ENTRIES = (
    Arm9ProfileEntry("DK4_TITLE_OPTIONS", 1276268, "設定", "Opts", "Title menu"),
    Arm9ProfileEntry("DK4_TITLE_CONTINUE", 1276400, "つづきから", "Continue", "Title menu"),
    Arm9ProfileEntry(
        "DK4_TITLE_EXTRAS",
        1276412,
        "おまけ機能",
        "Extras\0Tools",
        "Title menu plus Common-menu Tools label at the shared +6 pointer",
        slot_size=12,
    ),
    Arm9ProfileEntry("DK4_TITLE_NEW_GAME", 1276424, "はじめから", "New Game", "Title menu"),
    Arm9ProfileEntry("DK4_TITLE_GALLERY", 1276436, "ギャラリー", "Gallery", "Title menu"),
    Arm9ProfileEntry("DK4_TITLE_RACE", 1276568, "大航海レース", "Grand Race", "Title menu"),
    Arm9ProfileEntry("DK4_BUTTON_BACK", 1160460, "戻る", "Back", "Shared controller prompts"),
    Arm9ProfileEntry("DK4_BUTTON_DONE", 1160476, "決定", "Done", "Shared controller prompts"),
    Arm9ProfileEntry("DK4_BUTTON_EDIT", 1160516, "変更", "Edit", "Shared controller prompts"),
    Arm9ProfileEntry(
        "DK4_SELECT_HEADING",
        1376976,
        "キャラクター選択",
        "Choose Captain",
        "Character selection",
    ),
)


CHARACTER_ENTRIES = (
    Arm9ProfileEntry("DK4_LIL_NAME", 1423728, "リル", "Lil", "Lil character record"),
    Arm9ProfileEntry("DK4_LIL_LAST", 1428632, "アーゴット", "Argot", "Lil character record"),
    Arm9ProfileEntry(
        "DK4_LIL_ORG", 1434148, "アーゴット商会", "Argot Co.", "Lil character record"
    ),
    Arm9ProfileEntry(
        "DK4_LIL_BIO_1",
        1375612,
        "商魂たくましいオランダの少女",
        "A bold Dutch merchant girl  ",
        "Lil biography",
        "Trailing spaces preserve the original line delimiter.",
    ),
    Arm9ProfileEntry(
        "DK4_LIL_BIO_2",
        1375641,
        "幼なじみの相棒カミルとともに、",
        "With childhood friend Camille,",
        "Lil biography",
    ),
    Arm9ProfileEntry(
        "DK4_LIL_BIO_3",
        1375672,
        "一旗揚げようと世界の海に飛び出す",
        "Sails the world to make her mark",
        "Lil biography",
    ),
    Arm9ProfileEntry(
        "DK4_RAPHAEL_NAME", 1428032, "ラファエル", "Raphael", "Raphael character record"
    ),
    Arm9ProfileEntry(
        "DK4_RAPHAEL_LAST", 1428572, "カストール", "Castor", "Raphael character record"
    ),
    Arm9ProfileEntry(
        "DK4_RAPHAEL_ORG",
        1434132,
        "カストール商会",
        "Castor Co.",
        "Raphael character record",
    ),
    Arm9ProfileEntry(
        "DK4_RAPHAEL_BIO_1",
        1375708,
        "船乗りに漠然と憧れるポルトガルの少年",
        "Portuguese youth dreaming of the sea",
        "Raphael biography",
    ),
    Arm9ProfileEntry(
        "DK4_RAPHAEL_BIO_2",
        1375745,
        "友人にそそのかされて海に出ることになる",
        "A friend urges him to sail the world. ",
        "Raphael biography",
        "Trailing space preserves the original line delimiter.",
    ),
    Arm9ProfileEntry(
        "DK4_RAPHAEL_BIO_3",
        1375784,
        "初めてプレイする方におすすめ",
        "Recommended for new players.",
        "Raphael biography",
    ),
    Arm9ProfileEntry("DK4_HODRAM_NAME", 1425716, "ホドラム", "Hodram", "Hodram character record"),
    Arm9ProfileEntry(
        "DK4_HODRAM_MIDDLE", 1426388, "ヨアキム", "Joachim", "Hodram character record"
    ),
    Arm9ProfileEntry(
        "DK4_HODRAM_LAST", 1433556, "ベルグストロン", "Bergstrom", "Hodram character record"
    ),
    Arm9ProfileEntry(
        "DK4_HODRAM_ORG",
        1435492,
        "ベルグストロン軍",
        "Bergstrom Fleet",
        "Hodram character record",
    ),
    Arm9ProfileEntry(
        "DK4_HODRAM_BIO_1",
        1375816,
        "再独立を果たしたスウェーデンの提督",
        "An admiral of newly free Sweden   ",
        "Hodram biography",
        "Trailing spaces preserve the original line delimiter.",
    ),
    Arm9ProfileEntry(
        "DK4_HODRAM_BIO_2",
        1375851,
        "海軍とは名ばかりの私掠艦隊を率いる",
        "Commands a navy of privateers     ",
        "Hodram biography",
        "Trailing spaces preserve the original line delimiter.",
    ),
    Arm9ProfileEntry(
        "DK4_HODRAM_BIO_3",
        1375886,
        "自国の艦隊を世界最強にすべく活動する",
        "Aims to make his fleet the strongest",
        "Hodram biography",
    ),
    Arm9ProfileEntry("DK4_MARIA_NAME", 1425456, "マリア", "Maria", "Maria character record"),
    Arm9ProfileEntry("DK4_MARIA_LAST", 1424056, "リー", "Lee", "Maria character record"),
    Arm9ProfileEntry("DK4_MARIA_ORG", 1424736, "リー家", "LiFam", "Maria character record"),
    Arm9ProfileEntry(
        "DK4_MARIA_BIO_1",
        1375924,
        "倭寇に苦しめられる人々を守るために",
        "Guards people from pirate raids   ",
        "Maria biography",
        "Trailing spaces preserve the original line delimiter.",
    ),
    Arm9ProfileEntry(
        "DK4_MARIA_BIO_2",
        1375959,
        "国法である鎖国政策をあえて無視し、",
        "Defying the national isolation law",
        "Maria biography",
    ),
    Arm9ProfileEntry(
        "DK4_MARIA_BIO_3",
        1375994,
        "私設艦隊を率いて戦う明（みん）の女提督",
        "A Ming admiral leading her own fleet  ",
        "Maria biography",
        "Trailing spaces preserve the original line delimiter.",
    ),
)

CHARACTER_UI_ENTRIES = (
    # Character display screen. These are a second table, separate from the
    # character records and shared controller captions translated earlier.
    Arm9ProfileEntry("DK4_SELECT_LABEL_NAME", 0x15029C, "名", "1st", "Character field label", slot_size=4),
    Arm9ProfileEntry(
        "DK4_SELECT_LABEL_MIDDLE",
        0x1502A0,
        "ミドルネーム",
        "Middle Name",
        "Character field label",
        slot_size=16,
    ),
    Arm9ProfileEntry("DK4_SELECT_LABEL_LAST", 0x1502B0, "姓", "Sur", "Character field label", slot_size=4),
    Arm9ProfileEntry(
        "DK4_SELECT_LABEL_FACTION",
        0x1502B4,
        "勢力名",
        "Faction",
        "Character field label",
        slot_size=8,
    ),
    Arm9ProfileEntry(
        "DK4_SELECT_BIRTH_FORMAT",
        0x1502BC,
        "%2d月%2d日　生まれ",
        "%2d/%2d Born",
        "Character birth-date row",
        slot_size=20,
    ),
    # Character-edit screen. Each row embeds its own copy of "変更".
    Arm9ProfileEntry(
        "DK4_SELECT_EDIT_BUTTON",
        0x14FBE0,
        "変更",
        "Edit",
        "Character-screen Y-button caption",
        slot_size=8,
    ),
    Arm9ProfileEntry(
        "DK4_SELECT_EDIT_NAME",
        0x14FC28,
        "名　変更　　　　　",
        "Name: Edit",
        "Character-edit row",
        slot_size=20,
    ),
    Arm9ProfileEntry(
        "DK4_SELECT_EDIT_MIDDLE",
        0x14FC3C,
        "ミドルネーム　変更",
        "Middle: Edit",
        "Character-edit row",
        slot_size=20,
    ),
    Arm9ProfileEntry(
        "DK4_SELECT_EDIT_LAST",
        0x14FC50,
        "姓　変更　　　　　",
        "Last: Edit",
        "Character-edit row",
        slot_size=20,
    ),
    Arm9ProfileEntry(
        "DK4_SELECT_EDIT_FACTION",
        0x14FC64,
        "勢力名　変更　　　",
        "Faction: Edit",
        "Character-edit row",
        slot_size=20,
    ),
    Arm9ProfileEntry(
        "DK4_SELECT_EDIT_BIRTHDAY",
        0x14FC78,
        "誕生日　変更　　　",
        "Birthday: Edit",
        "Character-edit row",
        slot_size=20,
    ),
    Arm9ProfileEntry(
        "DK4_SELECT_POPUP_DONE",
        0x1502E4,
        "完了",
        "Done",
        "Character editor X-button caption",
        slot_size=8,
    ),
    Arm9ProfileEntry(
        "DK4_SELECT_BIRTH_MONTH_SUFFIX",
        0x150378,
        "月\n",
        "M\n",
        "Numeric month suffix shared by all twelve birthday-calendar months",
        slot_size=4,
    ),
    Arm9ProfileEntry(
        "DK4_SELECT_BIRTH_HEADING",
        0x15037C,
        "誕生日",
        "Birth",
        "Birthday calendar heading; the dedicated input patch repoints this to Birthday",
        slot_size=8,
    ),
)


CITY_SCREEN_ENTRIES = (
    Arm9ProfileEntry(
        "DK4_COMMON_INFO",
        0x11B504,
        "情報",
        "Info",
        "Common radial-menu command",
        slot_size=8,
    ),
    Arm9ProfileEntry(
        "DK4_CITY_COMMON",
        0x11B57C,
        "共通",
        "Common",
        "City screen shared-information button",
        slot_size=8,
    ),
    Arm9ProfileEntry(
        "DK4_CITY_STATUS_NORMAL",
        0x1565D8,
        "通常",
        "Normal",
        "City status value",
        slot_size=8,
    ),
    Arm9ProfileEntry(
        "DK4_CITY_STATUS_NORMAL_VISIBLE",
        0x15633C,
        "通常",
        "Normal",
        "City status value used by the Lisbon information screen",
        slot_size=8,
    ),
    Arm9ProfileEntry("DK4_CITY_TYPE_CITY", 0x1565E4, "都市", "City", "City type value"),
    Arm9ProfileEntry(
        "DK4_CITY_HEADINGS",
        0x15692C,
        "種類状態発展度武装度",
        "TypeStatGrowthArms  ",
        "City information headings",
        "Four fixed fields: Type, Stat, Growth, Arms.",
    ),
    Arm9ProfileEntry("DK4_CITY_DIRECTION_EAST", 0x15690C, "東", "E", "City longitude direction", slot_size=4),
    Arm9ProfileEntry("DK4_CITY_DIRECTION_WEST", 0x156910, "西", "W", "City longitude direction", slot_size=4),
    Arm9ProfileEntry("DK4_CITY_DIRECTION_SOUTH", 0x156914, "南", "S", "City latitude direction", slot_size=4),
    Arm9ProfileEntry("DK4_CITY_DIRECTION_NORTH", 0x156918, "北", "N", "City latitude direction", slot_size=4),
    # Three earlier screens keep private copies of the same compass table.
    # Patching all copies prevents a palace/report screen from falling back to
    # Japanese even when the main town-information table is translated.
    Arm9ProfileEntry("DK4_DIRECTION_A_EAST", 0x140480, "東", "E", "Alternate coordinate direction", slot_size=4),
    Arm9ProfileEntry("DK4_DIRECTION_A_WEST", 0x140484, "西", "W", "Alternate coordinate direction", slot_size=4),
    Arm9ProfileEntry("DK4_DIRECTION_A_SOUTH", 0x140488, "南", "S", "Alternate coordinate direction", slot_size=4),
    Arm9ProfileEntry("DK4_DIRECTION_A_NORTH", 0x14048C, "北", "N", "Alternate coordinate direction", slot_size=4),
    Arm9ProfileEntry("DK4_DIRECTION_B_WEST", 0x143B24, "西", "W", "Alternate coordinate direction", slot_size=4),
    Arm9ProfileEntry("DK4_DIRECTION_B_SOUTH", 0x143B28, "南", "S", "Alternate coordinate direction", slot_size=4),
    Arm9ProfileEntry("DK4_DIRECTION_B_EAST", 0x143B2C, "東", "E", "Alternate coordinate direction", slot_size=4),
    Arm9ProfileEntry("DK4_DIRECTION_B_NORTH", 0x143B30, "北", "N", "Alternate coordinate direction", slot_size=4),
    Arm9ProfileEntry("DK4_DIRECTION_C_EAST", 0x14C27C, "東", "E", "Alternate coordinate direction", slot_size=4),
    Arm9ProfileEntry("DK4_DIRECTION_C_WEST", 0x14C280, "西", "W", "Alternate coordinate direction", slot_size=4),
    Arm9ProfileEntry("DK4_DIRECTION_C_SOUTH", 0x14C284, "南", "S", "Alternate coordinate direction", slot_size=4),
    Arm9ProfileEntry("DK4_DIRECTION_C_NORTH", 0x14C288, "北", "N", "Alternate coordinate direction", slot_size=4),
    Arm9ProfileEntry(
        "DK4_MAP_COORDINATE_FORMAT",
        0x140490,
        "%s緯 %3dﾟ %s経 %3dﾟ ",
        "%s %3d  %s %3d",
        "Map callout latitude/longitude format",
        slot_size=24,
    ),
    Arm9ProfileEntry(
        "DK4_MAP_MULTIPLE_CITIES",
        0x14C0E4,
        "など",
        " etc.",
        "Map callout suffix when a marker represents multiple cities",
        slot_size=8,
    ),
    Arm9ProfileEntry(
        "DK4_CITY_COORDINATE_FORMAT",
        0x15691C,
        "（%s%d%s%d）",
        "(%s%d %s%d)",
        "Shared city latitude/longitude format",
        slot_size=16,
    ),
    Arm9ProfileEntry(
        "DK4_CITY_PORT",
        0x156AEC,
        "出港所",
        "Port",
        "City location button",
        slot_size=8,
    ),
    Arm9ProfileEntry(
        "DK4_GOOD_SALT",
        0x15B78C,
        "塩",
        "Sal",
        "Fallback fixed-slot spelling; the post-build patch redirects the live pointer to full Salt.",
        slot_size=4,
    ),
    Arm9ProfileEntry("DK4_GOOD_GUNS", 0x15BAE8, "鉄砲", "Guns", "Commodity name"),
    Arm9ProfileEntry(
        "DK4_CITY_LISBON_A",
        0x15C068,
        "リスボン",
        "Lisbon",
        "Lisbon city-name slot",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_CITY_LISBON_B",
        0x15C11C,
        "リスボン",
        "Lisbon",
        "Lisbon city-name slot",
        slot_size=12,
    ),
    Arm9ProfileEntry("DK4_GOOD_SAFFRON", 0x15C1AC, "サフラン", "Saffron", "Commodity name"),
    Arm9ProfileEntry("DK4_GOOD_ALMOND", 0x15D550, "アーモンド", "Almond", "Commodity name"),
    Arm9ProfileEntry("DK4_GOOD_OLIVE_OIL", 0x15D58C, "オリーブ油", "Olive Oil", "Commodity name"),
    Arm9ProfileEntry("DK4_ROLE_KING_A", 0x15B878, "国王", "King", "Shared palace speaker role", slot_size=8),
    Arm9ProfileEntry("DK4_ROLE_GOVERNOR", 0x15B8B0, "総督", "Gov.", "Shared governor speaker role", slot_size=8),
    Arm9ProfileEntry("DK4_ROLE_KING_B", 0x15BB98, "国王", "King", "Shared palace speaker role", slot_size=8),
)


MENU_ENTRIES = (
    # Reusable command labels.
    Arm9ProfileEntry("DK4_MENU_INDEX", 0x11B524, "目次", "Index", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_SEARCH", 0x11B52C, "探索", "Search", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_MIN", 0x11B534, "最小", "Lo", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_NEXT", 0x11B53C, "次頁", "Next", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_ASSIGN", 0x11B54C, "配置", "Assign", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_DONE", 0x11B554, "完了", "Done", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_DELETE", 0x11B55C, "削除", "Delete", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_EQUIP", 0x11B564, "装備", "Equip", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_USE", 0x11B56C, "使う", "Use", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_PREV", 0x11B574, "前頁", "Prev", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_FACTION", 0x11B584, "勢力", "Faction", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_QUIT", 0x11B58C, "終了", "Quit", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_DECLARE", 0x11B594, "宣戦", "Declare", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_MAX", 0x11B59C, "最大", "Hi", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_STAFF", 0x11B5A4, "人事", "Staff", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_WORLD", 0x11B5AC, "世界", "World", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_WITHDRAW", 0x11B5B4, "全搬出", "Withdraw", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_REMOVE", 0x11B5BC, "はずす", "Remove", "Common menu command", slot_size=8),
    Arm9ProfileEntry("DK4_MENU_SORT", 0x11B5C4, "ソート", "Sort", "Common menu command", slot_size=8),
    Arm9ProfileEntry(
        "DK4_COMMON_ROUTE_MAP",
        0x137974,
        "航路図",
        "Map",
        "Common radial-menu command",
        slot_size=8,
    ),
    Arm9ProfileEntry("DK4_COMMON_ITEMS_A", 0x1389E0, "アイテム", "Items", "Shared item command", slot_size=12),
    Arm9ProfileEntry("DK4_COMMON_ITEMS_B", 0x138A04, "アイテム", "Items", "Shared item command", slot_size=12),
    Arm9ProfileEntry("DK4_COMMON_ITEMS_C", 0x138A58, "アイテム", "Items", "Shared item command", slot_size=12),
    Arm9ProfileEntry("DK4_COMMON_ITEMS_D", 0x13E2EC, "アイテム", "Items", "Shared item command", slot_size=12),
    Arm9ProfileEntry("DK4_COMMON_ITEMS_E", 0x13E300, "アイテム", "Items", "Shared item command", slot_size=12),
    # Deck screen rooms and policies.
    Arm9ProfileEntry("DK4_DECK_ADD_ROOM", 0x12FFC0, "追加１", "Add 1", "Deck room label", slot_size=8),
    Arm9ProfileEntry("DK4_DECK_NURSERY", 0x12FFC8, "飼育室", "Nursery", "Deck room label", slot_size=8),
    Arm9ProfileEntry("DK4_DECK_LOUNGE", 0x12FFD0, "娯楽室", "Lounge", "Deck room label", slot_size=8),
    Arm9ProfileEntry("DK4_DECK_MATE", 0x12FFD8, "副官室", "Mate", "Deck room label", slot_size=8),
    Arm9ProfileEntry("DK4_DECK_CAPTAIN", 0x12FFE0, "艦長室", "Captain", "Deck room label", slot_size=8),
    Arm9ProfileEntry("DK4_DECK_LOOKOUT", 0x12FFE8, "見張台", "Lookout", "Deck room label", slot_size=8),
    Arm9ProfileEntry("DK4_DECK_CARGO", 0x12FFF0, "積荷倉庫", "Cargo", "Deck room label", slot_size=12),
    Arm9ProfileEntry("DK4_DECK_MARINES", 0x12FFFC, "海兵詰所", "Marines", "Deck room label", slot_size=12),
    Arm9ProfileEntry("DK4_DECK_GUN_DECK", 0x130008, "武装砲台", "Gun Deck", "Deck room label", slot_size=12),
    Arm9ProfileEntry("DK4_DECK_SUPPLIES", 0x130014, "物資倉庫", "Supplies", "Deck room label", slot_size=12),
    Arm9ProfileEntry("DK4_POLICY_BATTLE", 0x130C84, "海戦", "Battle", "Deck policy", slot_size=8),
    Arm9ProfileEntry("DK4_POLICY_TRADE", 0x130C8C, "交易", "Trade", "Deck policy", slot_size=8),
    Arm9ProfileEntry("DK4_POLICY_EXPLORE", 0x130CA0, "探検航海", "Explore", "Deck policy", slot_size=12),
    # Crew assignment screen labels.
    Arm9ProfileEntry("DK4_DECK_CREW_SETUP", 0x131EDC, "人事配置", "Crew Setup", "Deck assignment heading", slot_size=12),
    Arm9ProfileEntry("DK4_DECK_UNASSIGNED", 0x131EE8, "未配置", "None", "Deck assignment status", slot_size=8),
    Arm9ProfileEntry("DK4_DECK_SKILL", 0x131EF8, "必要技能　%s", "Skill: %s", "Deck requirement label", slot_size=16),
    Arm9ProfileEntry("DK4_DECK_NEED_NONE", 0x131F08, "必要値　　－－", "Need: --", "Deck requirement label", slot_size=16),
    Arm9ProfileEntry("DK4_DECK_NEED_VALUE", 0x131F18, "必要値　　%4d", "Need: %4d", "Deck requirement label", slot_size=16),
    Arm9ProfileEntry("DK4_DECK_VIEW_A", 0x131F30, "甲板画面", "Deck View", "Deck screen heading", slot_size=12),
    Arm9ProfileEntry("DK4_DECK_VIEW_B", 0x131F3C, "甲板画面", "Deck View", "Deck screen heading", slot_size=12),
    Arm9ProfileEntry("DK4_DECK_VIEW_C", 0x132044, "甲板画面", "Deck View", "Deck screen heading", slot_size=12),
    Arm9ProfileEntry("DK4_CREW_ASSIGN_BUTTON_A", 0x134E30, "水夫編成", "Assign", "Ship screen crew-assignment button", slot_size=12),
    Arm9ProfileEntry("DK4_FLEET_ARRANGE_BUTTON", 0x143C18, "隊列変更", "Arrange", "Ship screen formation button", slot_size=12),
    Arm9ProfileEntry("DK4_FLEET_APPOINT_CAPTAIN", 0x143C30, "艦長任命", "Captain", "Fleet submenu command", slot_size=12),
    Arm9ProfileEntry(
        "DK4_FLEET_CREATE",
        0x143C3C,
        "地方艦隊作成",
        "Create Fleet",
        "Fleet submenu command",
        slot_size=16,
    ),
    Arm9ProfileEntry(
        "DK4_FLEET_SETUP",
        0x143C4C,
        "地方艦隊編成",
        "    Fleet Setup",
        "Fleet submenu command; the radial menu points four bytes into this slot",
        slot_size=16,
    ),
    Arm9ProfileEntry("DK4_FLEET_SWAP", 0x143C5C, "船の入れ替え", "Swap Ships", "Fleet submenu command", slot_size=16),
    Arm9ProfileEntry("DK4_FLEET_DISBAND", 0x143C6C, "地方艦隊解散", "Disband", "Fleet submenu command", slot_size=16),
    # City navigation menu.
    Arm9ProfileEntry("DK4_NAV_DEPART_A", 0x144644, "出港", "Depart", "City navigation menu", slot_size=8),
    Arm9ProfileEntry("DK4_NAV_DEPART_B", 0x14464C, "出港", "Depart", "City navigation menu", slot_size=8),
    Arm9ProfileEntry("DK4_NAV_SAIL_A", 0x144654, "洋上へ", "Sail", "City navigation menu", slot_size=8),
    Arm9ProfileEntry("DK4_NAV_SAIL_B", 0x14465C, "洋上へ", "Sail", "City navigation menu", slot_size=8),
    Arm9ProfileEntry("DK4_NAV_DOCK_A", 0x144664, "ドック", "Dock", "City navigation menu", slot_size=8),
    Arm9ProfileEntry("DK4_NAV_DOCK_B", 0x144674, "ドック", "Dock", "City navigation menu", slot_size=8),
    Arm9ProfileEntry("DK4_NAV_DECK_A", 0x144684, "甲板画面", "Deck View", "City navigation menu", slot_size=12),
    Arm9ProfileEntry("DK4_NAV_AUTO_A", 0x144690, "自動移動", "Auto Move", "City navigation menu", slot_size=12),
    Arm9ProfileEntry("DK4_NAV_DECK_B", 0x14469C, "甲板画面", "Deck View", "City navigation menu", slot_size=12),
    Arm9ProfileEntry("DK4_NAV_AUTO_B", 0x1446A8, "自動移動", "Auto Move", "City navigation menu", slot_size=12),
    Arm9ProfileEntry("DK4_NAV_CARGO_SETUP_A", 0x1446B4, "積み荷編成", "Cargo Setup", "City navigation menu", slot_size=12),
    Arm9ProfileEntry("DK4_NAV_CARGO_SETUP_B", 0x1446C0, "積み荷編成", "Cargo Setup", "City navigation menu", slot_size=12),
    # Shipyard main menu and its first-level submenus.
    Arm9ProfileEntry("DK4_YARD_REPAIR", 0x144754, "修理", "Repair", "Shipyard command", slot_size=8),
    Arm9ProfileEntry("DK4_YARD_REMODEL", 0x14475C, "改造", "Remodel", "Shipyard command", slot_size=8),
    Arm9ProfileEntry("DK4_YARD_SELL", 0x144764, "売却", "Sell", "Shipyard command", slot_size=8),
    Arm9ProfileEntry("DK4_YARD_BUY", 0x14476C, "購入", "Buy", "Shipyard command", slot_size=8),
    Arm9ProfileEntry("DK4_YARD_DOCK", 0x144774, "ドック", "Dock", "Shipyard command", slot_size=8),
    Arm9ProfileEntry("DK4_YARD_SPECIAL_ORDER", 0x144784, "特別注文", "Special", "Shipyard submenu command", slot_size=12),
    Arm9ProfileEntry("DK4_YARD_EQUIPMENT", 0x144790, "装備変更", "Equipment", "Shipyard submenu command", slot_size=12),
    Arm9ProfileEntry("DK4_YARD_RENAME", 0x14479C, "船名変更", "Rename", "Shipyard submenu command", slot_size=12),
    Arm9ProfileEntry("DK4_YARD_STANDARD_HULL", 0x1447A8, "標準船体", "Standard", "Shipyard submenu command", slot_size=12),
    # Ship-list headers have unusually wide Japanese-space padding.
    Arm9ProfileEntry("DK4_SHIP_LIST_FLEET_A", 0x151714, "隊列　　　　　　　　", "Fleet", "Ship-list column heading", slot_size=20),
    Arm9ProfileEntry("DK4_SHIP_LIST_DOCK_A", 0x151728, "ドック", "Dock", "Ship-list column heading", slot_size=8),
    Arm9ProfileEntry("DK4_SHIP_LIST_FLEET_B", 0x151730, "隊列　　　　　　　　", "Fleet", "Ship-list column heading", slot_size=20),
    Arm9ProfileEntry("DK4_SHIP_LIST_FLEET_C", 0x15174C, "隊列　　　　　　　　", "Fleet", "Ship-list column heading", slot_size=20),
    Arm9ProfileEntry("DK4_SHIP_LIST_DOCK_B", 0x151760, "ドック", "Dock", "Ship-list column heading", slot_size=8),
    Arm9ProfileEntry("DK4_CREW_ASSIGN_BUTTON_B", 0x151630, "水夫編成", "Assign", "Ship-list crew-assignment button", slot_size=12),
    # Shipyard list and ship-information formatters. These suffixes are drawn
    # after already-translated ship names and otherwise leave mixed strings
    # such as "Latina号" and "Latina級".
    Arm9ProfileEntry("DK4_SHIP_NAME_FORMAT_A", 0x133FFC, "%s号", "%s", "Ship name formatter", slot_size=8),
    Arm9ProfileEntry("DK4_SHIP_CLASS_FORMAT_A", 0x134004, "%14s級", "%14s", "Ship class formatter", slot_size=8),
    Arm9ProfileEntry("DK4_SHIP_PRICE_CLASS_FORMAT", 0x1514B0, "%14s級", "%14s", "Shipyard class heading", slot_size=8),
    Arm9ProfileEntry("DK4_SHIP_PRICE_FORMAT_A", 0x1514B8, "金貨%10d枚", "%10d coins", "Shipyard price", slot_size=12),
    Arm9ProfileEntry("DK4_SHIP_PRICE_FORMAT_B", 0x1514C4, "金貨%10d枚", "%10d coins", "Shipyard price", slot_size=12),
    Arm9ProfileEntry("DK4_SHIP_NAME_FORMAT_B", 0x1514E0, "%s号", "%s", "Shipyard ship name formatter", slot_size=8),
    Arm9ProfileEntry("DK4_SHIP_CLASS_FORMAT_B", 0x1514E8, "%14s級", "%14s", "Shipyard ship class formatter", slot_size=8),
    Arm9ProfileEntry("DK4_SHIP_NAME_FORMAT_C", 0x152BC8, "%s号", "%s", "Ship purchase name formatter", slot_size=8),
    Arm9ProfileEntry("DK4_SHIP_CLASS_FORMAT_C", 0x152BD0, "%14s級", "%14s", "Ship purchase class formatter", slot_size=8),
    Arm9ProfileEntry("DK4_SHIP_GUN_FORMAT_A", 0x134034, "%s砲", "%s", "Ship gun-type formatter", slot_size=8),
    Arm9ProfileEntry("DK4_SHIP_GUN_COUNT_A", 0x13403C, "%d門", "%d", "Ship gun-count formatter", slot_size=8),
    Arm9ProfileEntry("DK4_SHIP_GUN_FORMAT_B", 0x151554, "%s砲", "%s", "Shipyard gun-type formatter", slot_size=8),
    Arm9ProfileEntry("DK4_SHIP_GUN_COUNT_B", 0x15155C, "%d門", "%d", "Shipyard gun-count formatter", slot_size=8),
    Arm9ProfileEntry("DK4_SHIP_GUN_FORMAT_C", 0x152C3C, "%s砲", "%s", "Ship-purchase gun-type formatter", slot_size=8),
    Arm9ProfileEntry("DK4_SHIP_GUN_COUNT_C", 0x152C44, "%d門", "%d", "Ship-purchase gun-count formatter", slot_size=8),
    Arm9ProfileEntry("DK4_SHIP_CLASS_FORMAT_D", 0x152C54, "%s級", "%s", "Ship-purchase class suffix", slot_size=8),
)

WORLD_CITY_ENTRIES = (
    Arm9ProfileEntry("DK4_CITY_SEVILLE", 0x15C080, "セビリア", "Seville", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_MALACCA_A", 0x15C128, "マラッカ", "Malacca", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_OVIEDO", 0x15C14C, "オビエド", "Oviedo", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_SOCOTRA", 0x15C170, "ソコトラ", "Socotra", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_ALGIERS", 0x15C23C, "アルジェ", "Algiers", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_SOFALA_A", 0x15C278, "ソファラ", "Sofala", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_MALACCA_B", 0x15C2C0, "マラッカ", "Malacca", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_SURABAYA", 0x15C3E0, "スラバヤ", "Surabaya", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_LONDON", 0x15C62C, "ロンドン", "London", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_LUANDA", 0x15C6EC, "ルアンダ", "Luanda", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_SOFALA_B", 0x15C758, "ソファラ", "Sofala", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_TUNIS", 0x15C800, "チュニス", "Tunis", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_MADEIRA", 0x15C818, "マディラ", "Madeira", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_TRIPOLI", 0x15C830, "トリポリ", "Tripoli", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_HAMBURG", 0x15CA34, "ハンブルク", "Hamburg", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_GENOA_A", 0x15CA64, "ジェノヴァ", "Genoa", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_VALENCIA", 0x15CC50, "バレンシア", "Valencia", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_GENOA_B", 0x15CC68, "ジェノヴァ", "Genoa", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_MARSEILLE", 0x15CC80, "マルセイユ", "Marseille", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_BRISTOL", 0x15CCD4, "ブリストル", "Bristol", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_BEIRUT", 0x15CCE0, "ベイルート", "Beirut", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_CALICUT", 0x15CD88, "カリカット", "Calicut", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_CALCUTTA", 0x15CDAC, "カルカッタ", "Calcutta", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_BATAVIA", 0x15CDDC, "バタヴィア", "Batavia", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_TERNATE", 0x15CDF4, "テルナーテ", "Ternate", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_JAMAICA", 0x15CE84, "ジャマイカ", "Jamaica", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_MARACAIBO", 0x15CEA8, "マラカイボ", "Maracaibo", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_MAKASSAR", 0x15CF50, "マカッサル", "Makassar", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_ALBACETE", 0x15CF5C, "アルバセテ", "Albacete", "World city name", slot_size=12),
    # Additional port, town, and settlement names from the shared world-name
    # table. These entries are reused by route maps, market reports, and
    # settlement/event screens.
    Arm9ProfileEntry("DK4_CITY_HANGZHOU_A", 0x15B7F8, "抗州", "Hangzhou", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_SEOUL_A", 0x15B870, "京城", "Seoul", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_OSAKA", 0x15B910, "大坂", "Osaka", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_NAGASAKI", 0x15BA80, "長崎", "Nagasaki", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_GOA", 0x15BA98, "ゴア", "Goa", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_NAHA", 0x15BAA8, "那覇", "Naha", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_HANGZHOU_B", 0x15BB20, "杭州", "Hangzhou", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_CEUTA", 0x15BBB8, "セウタ", "Ceuta", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_ATHENS", 0x15BBD8, "アテネ", "Athens", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_OSLO", 0x15BC60, "オスロ", "Oslo", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_MERIDA", 0x15BCA8, "メリダ", "Merida", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_BASRA_A", 0x15BCD0, "バスラ", "Basra", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_GUAM", 0x15BD00, "グアム", "Guam", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_BAHAMAS", 0x15BE08, "バハマ", "Bahama", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_ADEN", 0x15BE50, "アデン", "Aden", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_AVA", 0x15BE68, "アヴァ", "Ava", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_NOME", 0x15BE78, "ノーム", "Nome", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_MACAO", 0x15BE98, "マカオ", "Macao", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_CORFU", 0x15BEC8, "コルフ", "Corfu", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_ACHIN", 0x15C008, "アチン", "Achin", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_HAWAII", 0x15C010, "ハワイ", "Hawaii", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_CRETE", 0x15C018, "クレタ", "Crete", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_SYRACUSE", 0x15C1DC, "シラクサ", "Syracuse", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_HORMUZ", 0x15C29C, "ホルムズ", "Hormuz", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_CAYENNE", 0x15C374, "カエンヌ", "Cayenne", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_MOMBASA", 0x15C398, "モンバサ", "Mombasa", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_MADRAS", 0x15C3B0, "マドラス", "Madras", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_CALLAO", 0x15C4A0, "カリャオ", "Callao", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_CEYLON", 0x15C5B4, "セイロン", "Ceylon", "World settlement name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_RAGUSA", 0x15C938, "ラグーサ", "Ragusa", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_CALICUT_B", 0x15CADC, "カリカット", "Calicut", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_JAKARTA", 0x15CAF4, "ジャカルタ", "Jakarta", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_BRUGES", 0x15CB90, "ブルージュ", "Bruges", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_PORTOBELO", 0x15CE90, "ポルトベロ", "Portobelo", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_TRUJILLO", 0x15CEC0, "トルヒーヨ", "Trujillo", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_SAO_TOME", 0x15CED8, "サン＝トメ", "Sao Tome", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_VERACRUZ_A", 0x15D6E4, "ヴェラクルス", "Veracruz", "World city name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_LUBECK", 0x15D744, "リューベック", "Lubeck", "World city name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_VENICE", 0x15D764, "ヴェネツィア", "Venice", "World city name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_LAS_PALMAS", 0x15D7C4, "ラスパルマス", "Las Palmas", "World city name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_CAPE_TOWN", 0x15D7F4, "ケープタウン", "Cape Town", "World city name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_MOGADISHU", 0x15D814, "モガディシオ", "Mogadishu", "World city name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_SAN_JUAN", 0x15D8F4, "サン＝ファン", "San Juan", "World city name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_VALPARAISO", 0x15D9C4, "バルバライソ", "Valparaiso", "World city name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_MONTEVIDEO", 0x15D9E4, "モンテビデオ", "Montevideo", "World city name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_VESTAROS", 0x15DA74, "ヴェスタロス", "Vestaros", "World settlement name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_STOCKHOLM_A", 0x15DE54, "ストックホルム", "Stockholm", "World city name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_AMSTERDAM_A", 0x15DE84, "アムステルダム", "Amsterdam", "World city name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_ISTANBUL", 0x15DEC4, "イスタンプール", "Istanbul", "World city name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_AMSTERDAM_B", 0x15DF94, "アムステルダム", "Amsterdam", "World city name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_COPENHAGEN", 0x15DFC4, "コペンハーゲン", "Copenhagen", "World city name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_RIGA", 0x15BA08, "リガ", "Riga", "World settlement name", slot_size=8),
    Arm9ProfileEntry("DK4_CITY_LINARES", 0x15C1A0, "リナレス", "Linares", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_KARIBIB", 0x15C44C, "カリビブ", "Karibib", "World settlement name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_BRUNEI", 0x15C4D0, "ブルネイ", "Brunei", "World settlement name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_NARVIK", 0x15C7E8, "ナルビク", "Narvik", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_CYPRUS", 0x15C908, "キプロス", "Cyprus", "World settlement name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_PENSACOLA", 0x15CF68, "ペンサコラ", "Pensacola", "World city name", slot_size=12),
    Arm9ProfileEntry("DK4_CITY_MADAGASCAR", 0x15D944, "マダガスカル", "Madagascar", "World settlement name", slot_size=16),
    Arm9ProfileEntry("DK4_CITY_MASULIPATAM", 0x15D964, "マスリパタム", "Masulipatam", "World city name", slot_size=16),
)

SHARED_STORY_ENTRIES = (
    # Early Raphael-story speaker names. These live in the shared ARM9 name pool,
    # so patching them also fixes name plates outside the opening scene.
    Arm9ProfileEntry(
        "DK4_NAME_JULIO",
        0x15BF28,
        "フリオ",
        "Julio",
        "Shared character-name pool",
        slot_size=8,
    ),
    Arm9ProfileEntry(
        "DK4_NAME_PASAR",
        0x15C060,
        "パサー",
        "Pasar",
        "Shared character surname pool",
        slot_size=8,
    ),
    Arm9ProfileEntry(
        "DK4_NAME_ERNECO_A",
        0x15C20C,
        "エルネコ",
        "Erneco",
        "Shared character surname pool",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_NAME_JANUS",
        0x15C710,
        "ジェナス",
        "Janus",
        "Shared character-name pool",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_NAME_MANAUS",
        0x15C914,
        "マナウス",
        "Manaus",
        "Shared character surname pool",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_NAME_ERNECO_B",
        0x15C9BC,
        "エルネコ",
        "Erneco",
        "Shared character surname pool",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_NAME_CLAUDIO",
        0x15D784,
        "クラウディオ",
        "Claudio",
        "Shared character-name pool",
        slot_size=16,
    ),
    Arm9ProfileEntry("DK4_NAME_JULIA", 0x15C9B0, "ジュリア", "Julia", "Shared character-name pool", slot_size=12),
    Arm9ProfileEntry("DK4_SHIP_CARTEIRA", 0x15D118, "カルテイラ", "Carteira", "Raphael's starting ship", slot_size=12),
    Arm9ProfileEntry("DK4_SHIP_CLASS_LATINA_A", 0x15D2BC, "ラティーナ", "Latina", "Global ship-class name", slot_size=12),
    Arm9ProfileEntry("DK4_SHIP_CLASS_LATINA_B", 0x15D4D8, "ラティーナ", "Latina", "Global ship-class name", slot_size=12),
    Arm9ProfileEntry("DK4_SHIP_CLASS_LATINA_C", 0x15E0A8, "ラティーナ", "Latina", "Global ship-class name", slot_size=12),
    Arm9ProfileEntry("DK4_SHIP_CLASS_RETONDA_A", 0x15C4F4, "レトンダ", "Retonda", "Global ship-class name", slot_size=12),
    Arm9ProfileEntry("DK4_SHIP_CLASS_RETONDA_B", 0x15C6D4, "レトンダ", "Retonda", "Global ship-class name", slot_size=12),
    Arm9ProfileEntry("DK4_SHIP_CLASS_RETONDA_C", 0x15D8E4, "武装レトンダ", "Armed Retonda", "Global armed ship-class name", slot_size=16),
    Arm9ProfileEntry("DK4_SHIP_CLASS_CARRACK_A", 0x15D2E0, "キャラック", "Carrack", "Global ship-class name", slot_size=12),
    Arm9ProfileEntry("DK4_SHIP_CLASS_CARRACK_B", 0x15D4F0, "キャラック", "Carrack", "Global ship-class name", slot_size=12),
    Arm9ProfileEntry("DK4_SHIP_CLASS_CARRACK_C", 0x15E0B4, "武装キャラック", "Armed Carrack", "Global armed ship-class name", slot_size=16),
    Arm9ProfileEntry(
        "DK4_FACTION_ALBUQUERQUE",
        0x15E244,
        "アルブケルケ軍",
        "Albuquerque",
        "Albuquerque faction name used by city information and map screens",
        slot_size=16,
    ),
    Arm9ProfileEntry("DK4_GUN_CULVERIN", 0x13C1A7, "カルバリン", "Culverin", "Global cannon-type table", slot_size=17),
    # City icon hover labels. Every record is an eight-byte terminated slot.
    Arm9ProfileEntry("DK4_PLACE_TAVERN", 0x156A9C, "酒場", "Tavern", "City location button", slot_size=8),
    Arm9ProfileEntry("DK4_PLACE_RUINS", 0x156AA4, "遺跡", "Ruins", "City location button", slot_size=8),
    Arm9ProfileEntry("DK4_PLACE_PALACE", 0x156AAC, "王宮", "Palace", "City location button", slot_size=8),
    Arm9ProfileEntry("DK4_PLACE_CHURCH", 0x156AB4, "教会", "Church", "City location button", slot_size=8),
    Arm9ProfileEntry("DK4_PLACE_INN", 0x156ABC, "宿屋", "Inn", "City location button", slot_size=8),
    Arm9ProfileEntry("DK4_PLACE_GATE", 0x156AC4, "城門", "Gate", "City location button", slot_size=8),
    Arm9ProfileEntry("DK4_PLACE_SQUARE", 0x156ACC, "広場", "Square", "City location button", slot_size=8),
    Arm9ProfileEntry("DK4_PLACE_GUILD", 0x156AD4, "ギルド", "Guild", "City location button", slot_size=8),
    Arm9ProfileEntry("DK4_PLACE_GOVERNOR", 0x156ADC, "総督府", "Govt", "City location button", slot_size=8),
    Arm9ProfileEntry("DK4_PLACE_SHIPYARD", 0x156AE4, "造船所", "Yard", "City location button", slot_size=8),
    Arm9ProfileEntry("DK4_PLACE_MARKET", 0x156AF4, "交易所", "Market", "City location button", slot_size=8),
    Arm9ProfileEntry("DK4_ROLE_TAVERN_PATRON_A", 0x15C518, "酒場の客", "Patron", "Shared tavern speaker role", slot_size=12),
    Arm9ProfileEntry("DK4_ROLE_TAVERN_PATRON_B", 0x15C53C, "酒場の客", "Patron", "Shared tavern speaker role", slot_size=12),
    Arm9ProfileEntry("DK4_ROLE_TAVERN_PATRON_C", 0x15C548, "酒場の客", "Patron", "Shared tavern speaker role", slot_size=12),
    Arm9ProfileEntry("DK4_ROLE_TAVERN_PATRON_D", 0x15C554, "酒場の客", "Patron", "Shared tavern speaker role", slot_size=12),
    Arm9ProfileEntry("DK4_ROLE_TAVERN_PATRON_E", 0x15C560, "酒場の客", "Patron", "Shared tavern speaker role", slot_size=12),
    Arm9ProfileEntry("DK4_ROLE_TAVERN_PATRON_F", 0x15C56C, "酒場の客", "Patron", "Shared tavern speaker role", slot_size=12),
    Arm9ProfileEntry("DK4_ROLE_TAVERN_PATRON_G", 0x15C578, "酒場の客", "Patron", "Shared tavern speaker role", slot_size=12),
    Arm9ProfileEntry("DK4_ROLE_TAVERN_PATRON_H", 0x15C5E4, "酒場の客", "Patron", "Shared tavern speaker role", slot_size=12),
    Arm9ProfileEntry("DK4_ROLE_TAVERN_PATRON_I", 0x15C614, "酒場の客", "Patron", "Shared tavern speaker role", slot_size=12),
)

# Ship models are duplicated across event, catalog, shipyard, fleet, and
# scenario pools.  Patch every known copy so scrolling a list cannot fall
# back to Japanese after the first few entries.
_SHIP_MODEL_SPECS = (
    (0x138984, "鉄甲船", "Ironclad", 8),
    (0x15B7F0, "ダウ", "Dhow", 8),
    (0x15B998, "ダウ", "Dhow", 8),
    (0x15BA88, "関船", "Sekibune", 8),
    (0x15BB18, "関船", "Sekibune", 8),
    (0x15BBD0, "ガレー", "Galley", 8),
    (0x15BBF8, "末次船", "Sueyoshi", 8),
    (0x15BC68, "バーク", "Barque", 8),
    (0x15BC80, "バーク", "Barque", 8),
    (0x15BCC0, "ケッチ", "Ketch", 8),
    (0x15BCE0, "鉄甲船", "Ironclad", 8),
    (0x15BDA0, "シップ", "Ship", 8),
    (0x15BDB8, "幽霊船", "Ghost", 8),
    (0x15BDE8, "安宅船", "Atake", 8),
    (0x15BE18, "ブリグ", "Brig", 8),
    (0x15BE20, "鉄甲船", "Ironclad", 8),
    (0x15BEE0, "ケッチ", "Ketch", 8),
    (0x15BEF8, "戦列艦", "LineShip", 8),
    (0x15BF10, "シップ", "Ship", 8),
    (0x15BF20, "ガレー", "Galley", 8),
    (0x15BF40, "戦列艦", "LineShip", 8),
    (0x15BF98, "幽霊船", "Ghost", 8),
    (0x15C020, "安宅船", "Atake", 8),
    (0x15C048, "ブリグ", "Brig", 8),
    (0x15C074, "武装関船", "Armed Seki", 12),
    (0x15C0F8, "ガレアス", "Galleass", 12),
    (0x15C224, "商用ナオ", "Trade Nao", 12),
    (0x15C314, "武装ナオ", "Armed Nao", 12),
    (0x15C5C0, "ジャンク", "Junk", 12),
    (0x15C5F0, "スループ", "Sloop", 12),
    (0x15C674, "ジャンク", "Junk", 12),
    (0x15C6F8, "ガレオン", "Galleon", 12),
    (0x15C704, "スループ", "Sloop", 12),
    (0x15C7C4, "ガレアス", "Galleass", 12),
    (0x15C7DC, "武装ダウ", "Armed Dhow", 12),
    (0x15C944, "ガレオン", "Galleon", 12),
    (0x15CA58, "小型ガレー", "Sm Galley", 12),
    (0x15CA94, "大型ガレー", "Lg Galley", 12),
    (0x15CAC4, "サムブーク", "Sambuk", 12),
    (0x15CB00, "スクーナー", "Schooner", 12),
    (0x15CB30, "フリゲート", "Frigate", 12),
    (0x15CBB4, "商用安宅船", "Trade Atake", 12),
    (0x15CBD8, "商用末次船", "Trade Suey.", 12),
    (0x15CBFC, "商用ブリグ", "Trade Brig", 12),
    (0x15CC44, "商用ケッチ", "Trade Ketch", 12),
    (0x15CC8C, "武装安宅船", "Armed Atake", 12),
    (0x15CCA4, "武装末次船", "Armed Suey.", 12),
    (0x15CCBC, "軍用鉄甲船", "War Ironclad", 12),
    (0x15CD64, "商用シップ", "Trade Ship", 12),
    (0x15CDA0, "コルベット", "Corvette", 12),
    (0x15CF08, "武装ケッチ", "Armed Ketch", 12),
    (0x15CF44, "武装ブリグ", "Armed Brig", 12),
    (0x15CF80, "軍用戦列艦", "War LineShip", 12),
    (0x15CFBC, "武装バーク", "Armed Barque", 12),
    (0x15CFE0, "武装シップ", "Armed Ship", 12),
    (0x15D010, "武装ガレー", "Armed Galley", 12),
    (0x15D208, "商用バーク", "Trade Barque", 12),
    (0x15D28C, "ハンザコグ", "Hanse Cog", 12),
    (0x15D2F8, "軽ガレオン", "Lt Galleon", 12),
    (0x15D304, "フリュート", "Fluyt", 12),
    (0x15D31C, "ピンネース", "Pinnace", 12),
    (0x15D358, "コルベット", "Corvette", 12),
    (0x15D370, "ジーベック", "Xebec", 12),
    (0x15D37C, "フリゲート", "Frigate", 12),
    (0x15D388, "スクーナー", "Schooner", 12),
    (0x15D3AC, "小型ガレー", "Sm Galley", 12),
    (0x15D3C4, "大型ガレー", "Lg Galley", 12),
    (0x15D3E8, "サムブーク", "Sambuk", 12),
    (0x15D3F4, "ジーベック", "Xebec", 12),
    (0x15D418, "ピンネース", "Pinnace", 12),
    (0x15D478, "フリュート", "Fluyt", 12),
    (0x15D4C0, "ハンザコグ", "Hanse Cog", 12),
    (0x15D4FC, "軽ガレオン", "Lt Galleon", 12),
    (0x15D644, "小型ジャンク", "Small Junk", 16),
    (0x15D664, "大型ジャンク", "Large Junk", 16),
    (0x15D724, "商用ガレオン", "Trade Galleon", 16),
    (0x15D7D4, "輸送用戦列艦", "Transport Line", 16),
    (0x15D844, "輸送用ガレー", "Transport Gal.", 16),
    (0x15D884, "商用ジャンク", "Trade Junk", 16),
    (0x15D8A4, "輸送用鉄甲船", "Transport Iron", 16),
    (0x15D934, "軍用ガレオン", "War Galleon", 16),
    (0x15D954, "武装スループ", "Armed Sloop", 16),
    (0x15DA04, "軍用ガレアス", "War Galleass", 16),
    (0x15DA44, "武装ジャンク", "Armed Junk", 16),
    (0x15DC64, "小型ジャンク", "Small Junk", 16),
    (0x15DCB4, "大型ジャンク", "Large Junk", 16),
    (0x15DE94, "バーケンティン", "Barquentine", 16),
    (0x15DF54, "商用キャラック", "Trade Carrack", 16),
    (0x15DF74, "商用軽ガレオン", "Trade LtGall.", 16),
    (0x15DFA4, "商用ピンネース", "Trade Pinnace", 16),
    (0x15DFF4, "商用フリュート", "Trade Fluyt", 16),
    (0x15E014, "商用スクーナー", "Trade Schooner", 16),
    (0x15E044, "輸送用ガレアス", "Transport Gal.", 16),
    (0x15E064, "商用サムブーク", "Trade Sambuk", 16),
    (0x15E074, "商用ジーベック", "Trade Xebec", 16),
    (0x15E094, "武装ハンザコグ", "Armed HanseCog", 16),
    (0x15E0C4, "軍用軽ガレオン", "War LtGalleon", 16),
    (0x15E0E4, "武装フリュート", "Armed Fluyt", 16),
    (0x15E104, "武装ピンネース", "Armed Pinnace", 16),
    (0x15E124, "軍用コルベット", "War Corvette", 16),
    (0x15E144, "軍用フリゲート", "War Frigate", 16),
    (0x15E164, "武装スクーナー", "Armed Schooner", 16),
    (0x15E174, "武装小型ガレー", "Armed SmGalley", 16),
    (0x15E184, "武装大型ガレー", "Armed LgGalley", 16),
    (0x15E1A4, "武装サムブーク", "Armed Sambuk", 16),
    (0x15E1B4, "武装ジーベック", "Armed Xebec", 16),
    (0x15E2A4, "ブリガンティン", "Brigantine", 16),
    (0x15E314, "バーケンティン", "Barquentine", 16),
    (0x15E434, "ブリガンティン", "Brigantine", 16),
    (0x15E638, "輸送用コルベット", "Transport Corvette", 20),
    (0x15E660, "輸送用フリゲート", "Transport Frigate", 20),
    (0x15E688, "輸送用大型ガレー", "Transport LgGalley", 20),
    (0x15E69C, "商用大型ジャンク", "Trade Large Junk", 20),
    (0x15E6EC, "武装小型ジャンク", "Armed Small Junk", 20),
    (0x15E700, "武装大型ジャンク", "Armed Large Junk", 20),
    (0x15E958, "商用ブリガンティン", "Trade Brigantine", 20),
    (0x15E980, "商用バーケンティン", "Trade Barquentine", 20),
    (0x15E994, "武装ブリガンティン", "Armed Brigantine", 20),
    (0x15E9A8, "武装バーケンティン", "Armed Barquentine", 20),
)

SHIP_MODEL_ENTRIES = tuple(
    Arm9ProfileEntry(
        f"DK4_SHIP_MODEL_{offset:06X}",
        offset,
        japanese,
        english,
        "Global ship-model table",
        slot_size=slot_size,
    )
    for offset, japanese, english, slot_size in _SHIP_MODEL_SPECS
)

TOWN_UI_ENTRIES = (
    # Faction archetypes substituted into tavern rumors.  These are separate
    # from the dialogue record, which is why leaving them Japanese produced
    # otherwise-English lines such as "Genoa's 商人".
    Arm9ProfileEntry(
        "DK4_FACTION_ROLE_PIRATE",
        0x137144,
        "海賊",
        "Pirate",
        "Faction archetype used by tavern rumors",
        slot_size=8,
    ),
    Arm9ProfileEntry(
        "DK4_FACTION_ROLE_MERCHANT",
        0x13714C,
        "商人",
        "Trader",
        "Faction archetype used by tavern rumors",
        slot_size=8,
    ),
    Arm9ProfileEntry(
        "DK4_FACTION_ROLE_SOLDIER",
        0x137154,
        "軍人",
        "Soldier",
        "Faction archetype used by tavern rumors",
        slot_size=8,
    ),
    # Tavern commands.
    Arm9ProfileEntry(
        "DK4_TAVERN_RECRUIT",
        0x143B90,
        "水夫を集める",
        "Recruit Crew",
        "Tavern command",
        slot_size=16,
    ),
    Arm9ProfileEntry(
        "DK4_TAVERN_TREAT",
        0x143BA0,
        "みんなにおごる",
        "Treat Everyone",
        "Tavern command",
        slot_size=16,
    ),
    Arm9ProfileEntry(
        "DK4_TAVERN_DRINK",
        0x143BB0,
        "飲み物をたのむ",
        "Order Drink",
        "Tavern command",
        slot_size=16,
    ),
    # Trading-post category menu. The game combines the category name with
    # the separate "%s店" formatter at runtime.
    Arm9ProfileEntry("DK4_SHOP_FORMAT", 0x14463C, "%s店", "%s Shop", "Trading-post category formatter", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_MEDICINE", 0x15A090, "薬", "Med", "Global trade category", slot_size=4),
    Arm9ProfileEntry("DK4_CATEGORY_DYES", 0x15A094, "染料", "Dyes", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_ARMS", 0x15A09C, "武器", "Arms", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_GOODS", 0x15A0A4, "雑貨", "Goods", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_SCENTS", 0x15A0AC, "香料", "Scents", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_DELICACIES", 0x15A0B4, "珍味", "Delic.", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_GEMS", 0x15A0BC, "宝石", "Gems", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_LIQUOR", 0x15A0C4, "酒類", "Liquor", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_ORE", 0x15A0CC, "鉱石", "Ore", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_TEXTILES", 0x15A0D4, "繊維", "Textile", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_LUXURY", 0x15A0DC, "贅沢品", "Luxury", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_FOOD", 0x15A0E4, "食料品", "Food", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_SEASONING", 0x15A0EC, "調味料", "Flavor", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_TREATS", 0x15A0F4, "嗜好品", "Treats", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_JEWELRY", 0x15A0FC, "装飾品", "Jewelry", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_METALS", 0x15A104, "貴金属", "Metals", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_CRAFTS", 0x15A10C, "工芸品", "Crafts", "Global trade category", slot_size=8),
    Arm9ProfileEntry("DK4_CATEGORY_SPICES", 0x15A114, "香辛料", "Spices", "Global trade category", slot_size=8),
    Arm9ProfileEntry(
        "DK4_PLAZA_TRENDS",
        0x143E98,
        "流行情報",
        "Trends",
        "Plaza shop-category menu",
        slot_size=12,
    ),
    # Palace / governor commands. These strings are shared by every city.
    Arm9ProfileEntry("DK4_PALACE_CONTRACT", 0x143DF4, "契約", "Contract", "Palace command", slot_size=8),
    Arm9ProfileEntry(
        "DK4_PALACE_MILITARY_INVEST",
        0x143E04,
        "軍事投資",
        "Mil Invest",
        "Palace command",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_PALACE_USE_RECOMMENDATION",
        0x143E1C,
        "推薦状を使う",
        "Use Recommend",
        "Palace command",
        slot_size=16,
    ),
    Arm9ProfileEntry(
        "DK4_PALACE_USE_LETTER",
        0x143E2C,
        "紹介状を使う",
        "Use Letter",
        "Palace command",
        slot_size=16,
    ),
    Arm9ProfileEntry(
        "DK4_PALACE_LEND_ITEM",
        0x143E3C,
        "アイテムを貸す",
        "Lend Item",
        "Palace command",
        slot_size=20,
    ),
    Arm9ProfileEntry(
        "DK4_PALACE_RECLAIM_ITEM",
        0x143E5C,
        "アイテムを引き取る",
        "Reclaim Item",
        "Palace command",
        slot_size=20,
    ),
    Arm9ProfileEntry(
        "DK4_PALACE_MILITARY_AMOUNT",
        0x143E70,
        "軍事投資額",
        "Mil. Invest",
        "Military-investment amount label",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_PALACE_CONTRACT_AMOUNT",
        0x143E7C,
        "契約金額",
        "Deal Amount",
        "Palace contract amount label",
        slot_size=12,
    ),
    Arm9ProfileEntry("DK4_PALACE_GOVERNOR_OFFICE", 0x157064, "総督府", "Govt", "Palace type", slot_size=8),
    Arm9ProfileEntry("DK4_PALACE_ROYAL_PALACE", 0x15706C, "王宮", "Palace", "Palace type", slot_size=8),
    # Repeated name-plate role used by tavern dialogue.
    Arm9ProfileEntry(
        "DK4_ROLE_BARKEEP_A",
        0x15D154,
        "酒場の親父",
        "Barkeep",
        "Shared speaker-role pool",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_ROLE_BARKEEP_B",
        0x15D160,
        "酒場の親父",
        "Barkeep",
        "Shared speaker-role pool",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_ROLE_BARKEEP_C",
        0x15D2A4,
        "酒場の親父",
        "Barkeep",
        "Shared speaker-role pool",
        slot_size=12,
    ),
    Arm9ProfileEntry("DK4_ROLE_TRADER_A", 0x15DAC4, "交易所の親父", "Trader", "Shared speaker-role pool", slot_size=16),
    Arm9ProfileEntry("DK4_ROLE_TRADER_B", 0x15DAD4, "交易所の親父", "Trader", "Shared speaker-role pool", slot_size=16),
    Arm9ProfileEntry("DK4_ROLE_TRADER_C", 0x15DAE4, "交易所の親父", "Trader", "Shared speaker-role pool", slot_size=16),
    Arm9ProfileEntry("DK4_ROLE_TRADER_D", 0x15DAF4, "交易所の親父", "Trader", "Shared speaker-role pool", slot_size=16),
    Arm9ProfileEntry("DK4_ROLE_TRADER_E", 0x15DB04, "交易所の親父", "Trader", "Shared speaker-role pool", slot_size=16),
    # Repeated name-plate role used by port and resupply dialogue.
    Arm9ProfileEntry("DK4_ROLE_PORT_WORKER_A", 0x15DB74, "出港所の兄貴", "Port Worker", "Shared speaker-role pool", slot_size=16),
    Arm9ProfileEntry("DK4_ROLE_PORT_WORKER_B", 0x15DB84, "出港所の兄貴", "Port Worker", "Shared speaker-role pool", slot_size=16),
    Arm9ProfileEntry("DK4_ROLE_PORT_WORKER_C", 0x15DB94, "出港所の兄貴", "Port Worker", "Shared speaker-role pool", slot_size=16),
    Arm9ProfileEntry("DK4_ROLE_PORT_WORKER_D", 0x15DBA4, "出港所の兄貴", "Port Worker", "Shared speaker-role pool", slot_size=16),
    Arm9ProfileEntry("DK4_ROLE_PORT_WORKER_E", 0x15DBB4, "出港所の兄貴", "Port Worker", "Shared speaker-role pool", slot_size=16),
    Arm9ProfileEntry("DK4_ROLE_PORT_WORKER_F", 0x15DBC4, "出港所の兄貴", "Port Worker", "Shared speaker-role pool", slot_size=16),
    Arm9ProfileEntry("DK4_ROLE_PORT_WORKER_G", 0x15DBD4, "出港所の兄貴", "Port Worker", "Shared speaker-role pool", slot_size=16),
    # Shared calendar and duration captions. These offsets feed every month,
    # not only the particular month visible when the screenshot was taken.
    Arm9ProfileEntry(
        "DK4_DURATION_DAYS_FORMAT",
        0x1331A0,
        "日数  %6d日",
        "Days: %6d",
        "Shared work-duration format",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_DURATION_APPROX_FORMAT",
        0x133FF4,
        "約%d日",
        "~%d d",
        "Approximate sailing-range format",
        slot_size=8,
    ),
    Arm9ProfileEntry("DK4_INN_3_DAYS", 0x143D78, "３日", "3 Days", "Inn duration option", slot_size=8),
    Arm9ProfileEntry("DK4_INN_30_DAYS", 0x143D88, "３０日", "30 Days", "Inn duration option", slot_size=8),
    Arm9ProfileEntry("DK4_INN_10_DAYS", 0x143D90, "１０日", "10 Days", "Inn duration option", slot_size=8),
    Arm9ProfileEntry(
        "DK4_INN_ONE_DAY",
        0x143DA0,
        "一日泊まる",
        "Stay 1 Day",
        "Inn duration command",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_INN_CONTINUE",
        0x143DAC,
        "続けて泊まる",
        "Stay More",
        "Inn duration command",
        slot_size=16,
    ),
    Arm9ProfileEntry("DK4_INN_LAST_MONTH", 0x143DCC, "先月", "Last Mo", "Inn report month", slot_size=8),
    Arm9ProfileEntry("DK4_INN_THIS_MONTH", 0x143DD4, "今月", "This Mo", "Inn report month", slot_size=8),
    Arm9ProfileEntry(
        "DK4_INN_MONTHS_AGO_A",
        0x143DDC,
        "%sカ月前",
        "%s Mo. Ago",
        "Inn report relative-month format",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_INN_MONTHS_AGO_B",
        0x143DE8,
        "%sカ月前",
        "%s Mo. Ago",
        "Inn report relative-month format",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_MARKET_ARRIVAL_MONTH_ALT",
        0x16AFB0,
        "入荷月",
        "Arr. Mo.",
        "Alternate shared arrival-month label",
        slot_size=8,
    ),
    # Shared confirmation buttons.
    Arm9ProfileEntry("DK4_BUTTON_NO", 0x133170, "いいえ", "No", "Yes/No prompt", slot_size=8),
    Arm9ProfileEntry("DK4_BUTTON_YES", 0x13317C, "はい", "Yes", "Yes/No prompt", slot_size=4),
    Arm9ProfileEntry("DK4_BUTTON_NO_ALT", 0x15AD10, "いいえ", "No", "Alternate Yes/No prompt", slot_size=8),
    Arm9ProfileEntry("DK4_BUTTON_YES_ALT", 0x15AD1C, "は い ", "Yes", "Alternate Yes/No prompt", slot_size=8),
    # Sailor-allocation screen.
    Arm9ProfileEntry(
        "DK4_CREW_COLUMNS",
        0x133FBC,
        "必要数　現在数　最大数",
        "Need   Now   Max",
        "Sailor allocation column headings",
        slot_size=24,
    ),
    Arm9ProfileEntry(
        "DK4_CREW_HEADING",
        0x133FD4,
        "水夫を編成して下さい",
        "Assign Sailors",
        "Sailor allocation heading",
        slot_size=24,
    ),
    Arm9ProfileEntry(
        "DK4_CREW_AUTO",
        0x1339F8,
        "自動",
        "Auto",
        "Automatic sailor allocation button",
        slot_size=8,
    ),
    Arm9ProfileEntry(
        "DK4_CREW_EVEN",
        0x133A00,
        "平均化",
        "Even",
        "Even sailor allocation button",
        slot_size=8,
    ),
    Arm9ProfileEntry(
        "DK4_CREW_FLAGSHIP",
        0x133A10,
        "旗艦重視",
        "Flagship",
        "Automatic sailor-allocation strategy",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_CREW_MINIMUM",
        0x133A1C,
        "必要最小",
        "Minimum",
        "Automatic sailor-allocation strategy",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_CREW_CAPTAIN_SUFFIX",
        0x13400C,
        "%s艦長",
        "%s Cap",
        "Captain suffix on sailor allocation screen",
        slot_size=8,
    ),
    # Shared faction and commodity records. These feed every city screen that
    # references the same global data table, including Seville.
    Arm9ProfileEntry("DK4_FACTION_VALDES", 0x15D214, "バルデス軍", "Valdes", "Global faction name", slot_size=12),
    Arm9ProfileEntry("DK4_GOOD_SULTANA", 0x15C9D4, "サルタナ", "Sultana", "Global commodity name", slot_size=12),
    Arm9ProfileEntry("DK4_GOOD_COTTON_CLOTH", 0x15BF90, "綿織物", "Cotton", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_ARMOR", 0x15B850, "甲冑", "Armor", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_FACTION_CLIFFORD", 0x15E234, "クリフォード軍", "Clifford", "Global faction name", slot_size=14),
    Arm9ProfileEntry("DK4_FACTION_ESPINOSA", 0x15E254, "エスピノサ商会", "Espinosa Co.", "Global faction name", slot_size=14),
    Arm9ProfileEntry("DK4_FACTION_NAGARPUR", 0x15E264, "ナガルプル商会", "Nagarpur Co.", "Global faction name", slot_size=14),
    Arm9ProfileEntry("DK4_FACTION_MALDONADO", 0x15E274, "マルドナード軍", "Maldonado", "Global faction name", slot_size=14),
    Arm9ProfileEntry("DK4_FACTION_PASHA", 0x15C638, "パシャ軍", "Pasha", "Global faction name", slot_size=8),
    Arm9ProfileEntry("DK4_FACTION_KUHN", 0x15D268, "クーン商会", "Kuhn", "Global faction name", slot_size=10),
    Arm9ProfileEntry("DK4_FACTION_KURUSHIMA", 0x15D280, "クルシマ家", "Kurushima", "Global faction name", slot_size=10),
    Arm9ProfileEntry("DK4_FACTION_PEREIRA", 0x15DC04, "ペレイラ商会", "Pereira", "Global faction name", slot_size=14),
    Arm9ProfileEntry("DK4_FACTION_ESCANTE", 0x15DC14, "エスカンテ軍", "Escante", "Global faction name", slot_size=14),
    Arm9ProfileEntry("DK4_GOOD_SAKE", 0x15B848, "清酒", "Sake", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_PLATINUM", 0x15B860, "白金", "Platinum", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_SOYBEANS", 0x15B880, "大豆", "Soybeans", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_BEEF", 0x15B8C0, "牛肉", "Beef", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_SILK", 0x15B930, "生糸", "Raw Silk", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_WHEAT", 0x15B938, "小麦", "Wheat", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_IVORY", 0x15B980, "象牙", "Ivory", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_PEARLS", 0x15B988, "真珠", "Pearls", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_WOOL", 0x15B9A0, "羊毛", "Wool", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_FRANKINCENSE", 0x15BA10, "乳香", "Incense", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_PAINTINGS", 0x15BA20, "絵画", "Artwork", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_SCULPTURES", 0x15BA28, "彫刻", "Statues", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_TIMBER", 0x15BA38, "木材", "Timber", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_FURS", 0x15BAD0, "毛皮", "Furs", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_COTTON", 0x15BB40, "綿花", "Cotton", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_FISH", 0x15BB48, "魚肉", "Fish", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_SUGAR", 0x15BB50, "砂糖", "Sugar", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_LEATHER", 0x15BB58, "皮革", "Leather", "Global commodity name", slot_size=8),
    Arm9ProfileEntry("DK4_GOOD_WHALE_MEAT", 0x15BB90, "鯨肉", "Whale", "Global commodity name", slot_size=8),
)

MARKET_UI_ENTRIES = (
    # Trading-post command menu and its repeated copies.
    Arm9ProfileEntry("DK4_MARKET_TRADE_A", 0x156FFC, "交易", "Trade", "Trading-post command", slot_size=8),
    Arm9ProfileEntry("DK4_MARKET_TRADE_B", 0x157004, "交易", "Trade", "Trading-post command", slot_size=8),
    # This slot is followed by live data rather than padding. Keep one byte for
    # the terminator or the renderer continues into the following structure.
    Arm9ProfileEntry("DK4_MARKET_SELL_ALL", 0x15700C, "全売", "SellAll", "Trading-post Y-button command", slot_size=8),
    Arm9ProfileEntry("DK4_MARKET_INVEST_A", 0x157024, "商業投資", "Invest", "Trading-post command", slot_size=12),
    Arm9ProfileEntry("DK4_MARKET_INVEST_B", 0x157030, "商業投資", "Invest", "Trading-post command", slot_size=12),
    Arm9ProfileEntry("DK4_MARKET_INFO_A", 0x15703C, "相場情報", "Market Info", "Trading-post command", slot_size=12),
    Arm9ProfileEntry("DK4_MARKET_INFO_B", 0x157048, "相場情報", "Market Info", "Trading-post command", slot_size=12),
    Arm9ProfileEntry(
        "DK4_MARKET_INVEST_AMOUNT",
        0x157074,
        "商業投資額",
        "Investment",
        "Commercial-investment label",
        slot_size=12,
    ),
    # Market report and trading summary screen.
    Arm9ProfileEntry("DK4_MARKET_INFO_HEADING", 0x159F6C, "相場情報", "Market Info", "Market-report heading", slot_size=12),
    Arm9ProfileEntry("DK4_MARKET_TOTAL_INCOME", 0x159FA4, "総収入", "Income", "Trading summary label", slot_size=8),
    # The trading-summary renderer clips single-byte text to the byte length of
    # the original Japanese label. These intentionally fit those visual limits.
    Arm9ProfileEntry("DK4_MARKET_TOTAL_EXPENSE", 0x159FAC, "総支出", "Spent", "Trading summary label", slot_size=8),
    Arm9ProfileEntry("DK4_MARKET_TOTAL", 0x159FB4, "合計", "Sum", "Trading summary label", slot_size=8),
    Arm9ProfileEntry("DK4_MARKET_TRADE_HEADING", 0x159FBC, "交易", "Deal", "Trading summary heading", slot_size=8),
    Arm9ProfileEntry("DK4_MARKET_BALANCE", 0x159FC4, "収支", "Net", "Trading summary heading", slot_size=8),
    Arm9ProfileEntry("DK4_MARKET_SHIP_NAME", 0x159FCC, "選択船名", "Ship", "Trading summary heading", slot_size=12),
    Arm9ProfileEntry("DK4_MARKET_CITY", 0x159FD8, "交易都市", "City", "Trading summary heading", slot_size=12),
    Arm9ProfileEntry("DK4_MARKET_GOOD_DETAILS", 0x159FE4, "交易品詳細", "Good Info", "Trading summary heading", slot_size=12),
    Arm9ProfileEntry("DK4_MARKET_SIZE", 0x159FF0, "規模", "Size", "Trading summary label", slot_size=8),
    Arm9ProfileEntry("DK4_MARKET_STATUS", 0x159FF8, "状態", "Status", "Trading summary label", slot_size=8),
    Arm9ProfileEntry("DK4_MARKET_ARRIVAL_MONTH", 0x15A000, "入荷月", "Arr. Mo.", "Trading summary label", slot_size=8),
    Arm9ProfileEntry("DK4_MARKET_FUNDS", 0x15A008, "所持金", "Funds", "Trading summary label", slot_size=8),
    # The renderer consumes the first byte after LF. A sacrificial space keeps
    # category names such as "Flavor" together on the second line.
    Arm9ProfileEntry(
        "DK4_MARKET_GOOD_SHARE_FORMAT_A",
        0x15A058,
        "%s\n%s%4d％",
        "%s\n %s%4d%",
        "Trade-good/category percentage format",
        slot_size=12,
    ),
    Arm9ProfileEntry(
        "DK4_MARKET_GOOD_SHARE_FORMAT_B",
        0x15A074,
        "%s\n%s%4d％",
        "%s\n %s%4d%",
        "Trade-good/category percentage format",
        slot_size=12,
    ),
    Arm9ProfileEntry("DK4_MARKET_REMAINING", 0x15A474, "残金", "Funds", "Shared investment funds label", slot_size=8),
    # Market-report map screen.
    Arm9ProfileEntry(
        "DK4_MARKET_MAP_FEE",
        0x14C04C,
        "%s\n閲覧料 金貨%s枚",
        "%s\n Fee: %s coins",
        "Market-report map fee",
        slot_size=20,
    ),
    Arm9ProfileEntry("DK4_MARKET_MAP_FACTION", 0x14C15C, "勢力", "Faction", "Market-report map button", slot_size=8),
    Arm9ProfileEntry("DK4_MARKET_MAP_WORLD", 0x14C17C, "世界", "World", "Market-report map button", slot_size=8),
)


# The shared name pool is used by portraits, dialogue name plates, officer
# lists, tavern recruitment, and several story paths.  Translating it here
# gives broad coverage without duplicating the same name in every script.
_GLOBAL_NAME_SPECS = (
    # Eight-byte records.
    (0x15B7B8, "ナオ", "Nao", 8),
    (0x15B840, "麗姫", "Reika", 8),
    (0x15B8E8, "春申", "Chun", 8),
    (0x15B8F0, "シン", "Shin", 8),
    (0x15B908, "ナオ", "Nao", 8),
    (0x15B9E0, "華昌", "Hua", 8),
    (0x15BA58, "アル", "Al", 8),
    (0x15BA78, "美華", "Mihwa", 8),
    (0x15BA90, "セラ", "Sera", 8),
    (0x15BAB0, "エメ", "Eme", 8),
    (0x15BAF8, "エス", "Es", 8),
    (0x15BB08, "ベイ", "Bei", 8),
    (0x15BB38, "ヤン", "Yan", 8),
    (0x15BB68, "ソル", "Sol", 8),
    (0x15BBA8, "カン", "Kan", 8),
    (0x15BBB0, "ホルヘ", "Jorge", 8),
    (0x15BBE8, "ペロー", "Perot", 8),
    (0x15BC08, "シドラ", "Sidra", 8),
    (0x15BC10, "カーン", "Khan", 8),
    (0x15BC18, "サリド", "Salid", 8),
    (0x15BC38, "ジャン", "Jean", 8),
    (0x15BC90, "フォン", "Fong", 8),
    (0x15BCA0, "ロペス", "Lopes", 8),
    (0x15BCF8, "パウロ", "Paulo", 8),
    (0x15BD08, "ユリス", "Yulis", 8),
    (0x15BD18, "ルシア", "Lucia", 8),
    (0x15BD30, "ヘクラ", "Hekla", 8),
    (0x15BD68, "クーン", "Kuhn", 8),
    (0x15BD88, "カルロ", "Carlo", 8),
    (0x15BDC0, "イブン", "Ibn", 8),
    (0x15BDF0, "イアン", "Ian", 8),
    (0x15BE00, "イファ", "Ifa", 8),
    (0x15BE38, "パシャ", "Pasha", 8),
    (0x15BE88, "シエン", "Xian", 8),
    (0x15BED0, "フアン", "Juan", 8),
    (0x15BEF0, "ワンダ", "Wanda", 8),
    (0x15BF08, "カミル", "Kamil", 8),
    (0x15BF38, "シモン", "Simon", 8),
    (0x15BF48, "ハンス", "Hans", 8),
    (0x15BF50, "ローサ", "Rosa", 8),
    (0x15BF60, "マリー", "Marie", 8),
    (0x15BF68, "ベリオ", "Berio", 8),
    (0x15BF80, "ネリー", "Nelly", 8),
    (0x15BF88, "トーニ", "Tony", 8),
    (0x15BFB8, "ディヴ", "Div", 8),
    (0x15BFC8, "ペドロ", "Pedro", 8),
    (0x15BFD0, "イブン", "Ibn", 8),
    (0x15BFD8, "シラキ", "Shira", 8),
    (0x15BFE0, "ジャン", "Jean", 8),
    (0x15C028, "ゲンツ", "Genz", 8),
    (0x15C040, "パオロ", "Paolo", 8),
    # Twelve-byte records.
    (0x15C0EC, "ゲオルグ", "Georg", 12),
    (0x15C164, "エンツォ", "Enzo", 12),
    (0x15C1B8, "グラウス", "Graus", 12),
    (0x15C1D0, "モライス", "Morais", 12),
    (0x15C218, "ロバート", "Robert", 12),
    (0x15C230, "マリヌス", "Marinus", 12),
    (0x15C254, "ユキヒサ", "Yukihisa", 12),
    (0x15C260, "ディオゴ", "Diogo", 12),
    (0x15C26C, "シルビア", "Silvia", 12),
    (0x15C284, "シナート", "Sinat", 12),
    (0x15C290, "ソウジン", "Sojin", 12),
    (0x15C2A8, "マヌエル", "Manuel", 12),
    (0x15C2B4, "ユリアン", "Julian", 12),
    (0x15C2D8, "ギルバン", "Gilban", 12),
    (0x15C2F0, "イサベル", "Isabel", 12),
    (0x15C308, "ザモリン", "Zamorin", 12),
    (0x15C320, "ペレイラ", "Pereira", 12),
    (0x15C32C, "アフマド", "Ahmad", 12),
    (0x15C338, "クルシマ", "Kurushima", 12),
    (0x15C344, "バスケス", "Vasquez", 12),
    (0x15C368, "ストーク", "Stork", 12),
    (0x15C38C, "アロンソ", "Alonso", 12),
    (0x15C3A4, "ムシャリ", "Mushari", 12),
    (0x15C3C8, "ナガヨシ", "Nagayoshi", 12),
    (0x15C3EC, "ガルシア", "Garcia", 12),
    (0x15C3F8, "ブランコ", "Blanco", 12),
    (0x15C410, "ブルーム", "Bloom", 12),
    (0x15C41C, "イヌビク", "Inuvik", 12),
    (0x15C428, "ジャコブ", "Jacob", 12),
    (0x15C434, "アギーレ", "Aguirre", 12),
    (0x15C440, "ザガノス", "Zaganos", 12),
    (0x15C458, "バルデス", "Valdes", 12),
    (0x15C464, "フォレル", "Forel", 12),
    (0x15C470, "ヤサール", "Yasar", 12),
    (0x15C47C, "ディニス", "Dinis", 12),
    (0x15C494, "シルウド", "Sirwood", 12),
    (0x15C4C4, "ミレール", "Miller", 12),
    (0x15C5D8, "ディアス", "Dias", 12),
    (0x15C620, "アルトス", "Altos", 12),
    (0x15C644, "シャルル", "Charles", 12),
    (0x15C7AC, "ヴェルデ", "Verde", 12),
    (0x15C7B8, "フォルク", "Volk", 12),
    (0x15C80C, "ジャック", "Jack", 12),
    (0x15C824, "ミハイル", "Mikhail", 12),
    (0x15C83C, "エイレネ", "Eirene", 12),
    (0x15C848, "イスカル", "Iscal", 12),
    (0x15C854, "クライブ", "Clive", 12),
    (0x15C860, "エルナン", "Hernan", 12),
    (0x15C8E4, "ラムジオ", "Ramusio", 12),
    (0x15C950, "マチルダ", "Matilda", 12),
    (0x15C98C, "エミリオ", "Emilio", 12),
    (0x15C9C8, "フェリド", "Ferid", 12),
    (0x15C9E0, "アフメト", "Ahmet", 12),
    (0x15C9EC, "プレット", "Prett", 12),
    (0x15CA7C, "ミュリネー", "Myrine", 12),
    (0x15CAD0, "ベナジール", "Benazir", 12),
    (0x15CAE8, "ティティス", "Titis", 12),
    (0x15CCB0, "ガジャルグ", "Gajarg", 12),
    (0x15CCF8, "ジガネマル", "Jiganemaru", 12),
    (0x15CD10, "ゲンジョウ", "Genjo", 12),
    (0x15CD1C, "チェザーレ", "Cesare", 12),
    (0x15CD28, "フェローグ", "Ferog", 12),
    (0x15CD34, "アンジェロ", "Angelo", 12),
    (0x15CD40, "プッチーニ", "Puccini", 12),
    (0x15CD4C, "ゲルハルト", "Gerhard", 12),
    (0x15CD7C, "サムウェル", "Samwell", 12),
    (0x15CD94, "アルメイダ", "Almeida", 12),
    (0x15CDB8, "アズィーザ", "Aziza", 12),
    (0x15CDC4, "ジェームズ", "James", 12),
    (0x15CDD0, "マルティン", "Martin", 12),
    (0x15CE0C, "ハードゥム", "Hardum", 12),
    (0x15CE24, "フェルナン", "Fernan", 12),
    (0x15CE30, "エスピノサ", "Espinosa", 12),
    (0x15CE3C, "アブラハン", "Abraham", 12),
    (0x15CE48, "ジェロニモ", "Geronimo", 12),
    (0x15CE54, "ナガルプル", "Nagarpur", 12),
    (0x15CE60, "ドゥアルテ", "Duarte", 12),
    (0x15CE6C, "ロペス・デ", "Lopes de", 12),
    (0x15CE78, "アントニー", "Antony", 12),
    (0x15CE9C, "エスカンテ", "Escante", 12),
    (0x15CEB4, "チャールズ", "Charles", 12),
    (0x15CECC, "ジウベルト", "Gilberto", 12),
    (0x15CEE4, "ファーズル", "Fazul", 12),
    (0x15CEF0, "レジオーニ", "Regioni", 12),
    (0x15CEFC, "アジャール", "Ajar", 12),
    (0x15CF20, "ジャウミー", "Jaume", 12),
    (0x15CF2C, "ギアデイン", "Giadin", 12),
    (0x15CF38, "ダヴィット", "David", 12),
    (0x15CF74, "アブハーズ", "Abhaz", 12),
    (0x15CF8C, "グラナート", "Granat", 12),
    (0x15CF98, "ジャックス", "Jacks", 12),
    (0x15CFA4, "ジュリアン", "Julian", 12),
    (0x15CFC8, "チャーチル", "Churchill", 12),
    (0x15CFD4, "ガブリエル", "Gabriel", 12),
    (0x15CFEC, "カルドッチ", "Cardocci", 12),
    (0x15CFF8, "ペラロンソ", "Peralonso", 12),
    (0x15D004, "ウィリアム", "William", 12),
    (0x15D01C, "リチャード", "Richard", 12),
    (0x15D028, "ディクソン", "Dixon", 12),
    (0x15D034, "レッツェル", "Letzel", 12),
    (0x15D04C, "レッツェル", "Letzel", 12),
    (0x15D058, "ダーマイー", "Damai", 12),
    (0x15D064, "レバキュー", "Lebeque", 12),
    (0x15D070, "ミヴォール", "Mivor", 12),
    (0x15D07C, "サンヒョン", "Sanghyeon", 12),
    (0x15D0AC, "ヴェリーサ", "Verisa", 12),
    (0x15D1D8, "ドゥーコフ", "Dukov", 12),
    (0x15D544, "ヒュイゲン", "Huygens", 12),
    (0x15D568, "エンジェル", "Angel", 12),
    (0x15D580, "ダンディー", "Dundee", 12),
    # Sixteen-byte records.
    (0x15D5B4, "マルグレーテ", "Margrete", 16),
    (0x15D5E4, "ファティシア", "Faticia", 16),
    (0x15D674, "フランシスカ", "Francisca", 16),
    (0x15D794, "クリスティナ", "Cristina", 16),
    (0x15D7A4, "エウドシオス", "Eudoxios", 16),
    (0x15D7B4, "ルドワイヤン", "Ludwyan", 16),
    (0x15D824, "フェルナンド", "Fernando", 16),
    (0x15D854, "クリフォード", "Clifford", 16),
    (0x15D864, "シュパイヤー", "Speyer", 16),
    (0x15D874, "アルブケルケ", "Albuquerque", 16),
    (0x15D894, "バルバロッサ", "Barbarossa", 16),
    (0x15D8B4, "ハイレディン", "Hayreddin", 16),
    (0x15D8C4, "シルヴェイラ", "Silveira", 16),
    (0x15D8D4, "ウッディーン", "Uddin", 16),
    (0x15D924, "マルドナード", "Maldonado", 16),
    (0x15D974, "ニヤーディー", "Niyadi", 16),
    (0x15D984, "フラーフェン", "Flahven", 16),
    (0x15D9A4, "ヴィルヘルム", "Wilhelm", 16),
    (0x15D9B4, "フェルメール", "Vermeer", 16),
    (0x15D9F4, "タウンゼント", "Townsend", 16),
    (0x15DA14, "シャルロット", "Charlotte", 16),
    (0x15E004, "アルカディウス", "Arcadius", 16),
    (0x15E024, "ロシュフォール", "Rochefort", 16),
    (0x15E034, "シャルバラーズ", "Shahrbaraz", 16),
    (0x15E054, "ヌレンナハール", "Nurennahar", 16),
    (0x15E084, "チェントリオネ", "Centurione", 16),
    (0x15E114, "アルナジュード", "Arnajud", 16),
)

GLOBAL_NAME_ENTRIES = tuple(
    Arm9ProfileEntry(
        f"DK4_GLOBAL_NAME_{offset:06X}",
        offset,
        japanese,
        english,
        "Shared global character-name pool",
        slot_size=slot_size,
    )
    for offset, japanese, english, slot_size in _GLOBAL_NAME_SPECS
)


PROFILES = {
    "startup": STARTUP_ENTRIES,
    "characters": CHARACTER_ENTRIES,
    "character_ui": CHARACTER_UI_ENTRIES,
    "city": CITY_SCREEN_ENTRIES,
    "menus": MENU_ENTRIES,
    "world": WORLD_CITY_ENTRIES,
    "shared": SHARED_STORY_ENTRIES,
    "ships": SHIP_MODEL_ENTRIES,
    "names": GLOBAL_NAME_ENTRIES,
    "town": TOWN_UI_ENTRIES,
    "market": MARKET_UI_ENTRIES,
    "all": STARTUP_ENTRIES
    + CHARACTER_ENTRIES
    + CHARACTER_UI_ENTRIES
    + CITY_SCREEN_ENTRIES
    + MENU_ENTRIES
    + WORLD_CITY_ENTRIES
    + SHARED_STORY_ENTRIES
    + SHIP_MODEL_ENTRIES
    + GLOBAL_NAME_ENTRIES
    + TOWN_UI_ENTRIES
    + MARKET_UI_ENTRIES,
}


def profile_names() -> tuple[str, ...]:
    return tuple(PROFILES)


def export_profile_rows(
    arm9: bytes, profile: str, include_drafts: bool = False
) -> list[dict[str, object]]:
    entries = PROFILES[profile]
    rows: list[dict[str, object]] = []
    for entry in entries:
        source = entry.expected_bytes
        actual = arm9[entry.offset : entry.offset + entry.source_length]
        if actual != source:
            raise ValueError(
                f"{entry.row_id}: ARM9 source mismatch at 0x{entry.offset:X}; "
                f"expected {source.hex().upper()}, found {actual.hex().upper()}"
            )
        rows.append(
            {
                "id": entry.row_id,
                "file_path": "/__arm9__.bin",
                "container_path": "",
                "encoding": "shift_jis",
                "source_offset": entry.offset,
                "source_length": entry.source_length,
                "source_hex": source.hex().upper(),
                "japanese": entry.japanese,
                "english": entry.suggested_english if include_drafts else "",
                "status": "draft" if include_drafts else "untranslated",
                "context": entry.context,
                "speaker": "",
                "notes": entry.notes,
                "max_bytes": entry.source_length,
                "allow_expand": "false",
                "pointer_group": "",
                "control_profile": "default",
                "wrap_width": 38,
            }
        )
    return rows
